/* やさしいいみ辞書（小学生向けの かんたんな ことば）。
   キー=英単語(小文字)。ここに無い語は アプリ側で ひらがな表示にフォールバック。
   随時 追加してOK。 */
const EASY = {
  /* どうし */
  "retire":"しごとを やめること",
  "breathe":"いきを すること",
  "improve":"もっと よくすること",
  "reduce":"へらすこと",
  "increase":"ふやすこと",
  "decrease":"へらすこと",
  "describe":"ことばで せつめいすること",
  "imagine":"あたまの なかで おもいうかべること",
  "achieve":"がんばって できるように なること",
  "prepare":"したくを すること",
  "protect":"まもること",
  "negotiate":"はなしあって きめること",
  "recommend":"いいよと すすめること",
  "respect":"あいてを たいせつに おもうこと",
  "suggest":"こうしたら？と いうこと",
  "realize":"ああそうか と きづくこと",
  "recognize":"みて だれ・なにか わかること",
  "require":"ぜったい ひつよう ということ",
  "provide":"よういして あげること",
  "produce":"つくりだすこと",
  "appreciate":"ありがたいと おもうこと",
  "apologize":"ごめんなさい と いうこと",
  "celebrate":"おいわいを すること",
  "complain":"ふまんを いうこと",
  "encourage":"がんばって！と おうえんすること",
  "expand":"おおきく ひろげること",
  "explore":"たんけんして しらべること",
  "hesitate":"どうしようか まよって ためらうこと",
  "maintain":"そのまま たもつこと",
  "observe":"よく みて しらべること",
  "participate":"いっしょに さんかすること",
  "persuade":"せっとくして なっとくさせること",
  "predict":"これから どうなるか いいあてること",
  "pretend":"〜の ふりを すること",
  "prevent":"おきないように ふせぐこと",
  "purchase":"おかねを はらって かうこと",
  "recover":"げんきに もどること",
  "remind":"おもいださせること",
  "replace":"べつのものと いれかえること",
  "represent":"だいひょうすること",
  "solve":"もんだいを とくこと",
  "struggle":"たいへんで がんばること",
  "survive":"いきのこること",
  "translate":"べつの ことばに なおすこと",
  "warn":"あぶないよ と しらせること",
  "admire":"すごいなと あこがれること",
  "afford":"おかねが あって かえること",
  "announce":"みんなに しらせること",
  "attend":"その ばしょに いくこと",
  "avoid":"ぶつからないように さけること",
  "behave":"おぎょうぎよく すること",
  "consider":"よく かんがえること",
  "contain":"なかに はいっていること",
  "demand":"つよく もとめること",
  "develop":"そだてて よくしていくこと",
  "discuss":"みんなで はなしあうこと",
  "distribute":"みんなに くばること",
  "estimate":"だいたい これくらい と よそうすること",
  "examine":"くわしく しらべること",
  "expect":"きっと こうなる と おもうこと",
  "express":"きもちを あらわすこと",
  "include":"なかに ふくむこと",
  "indicate":"これだよ と しめすこと",
  "inform":"しらせること",
  "inspire":"やるきを わかせること",
  "intend":"そうしよう と おもうこと",
  "invest":"おかねを つかって ふやそうとすること",
  "manage":"なんとか うまく やること",
  "measure":"ながさや おもさを はかること",
  "mention":"ちょっと いうこと",
  "obtain":"てに いれること",
  "operate":"きかいを うごかすこと",
  "organize":"きちんと まとめること",
  "perform":"みんなの まえで えんじること",
  "permit":"いいよ と ゆるすこと",
  "prove":"ほんとうだ と しめすこと",
  "publish":"ほんなどを だすこと",
  "react":"なにかに たいして うごくこと",
  "refuse":"いやだ と ことわること",
  "regret":"ああすれば よかった と おもうこと",
  "release":"そとに だす・はなすこと",
  "remove":"とりのぞくこと",
  "repair":"こわれたものを なおすこと",
  "respond":"へんじを すること",
  "reveal":"かくれていたものを みせること",
  "satisfy":"まんぞくさせること",
  "seek":"さがし もとめること",
  "select":"えらぶこと",
  "settle":"おちつく・かたづけること",
  "share":"みんなで わけあうこと",
  "spread":"ひろがること",
  "supply":"ひつようなものを あたえること",
  "support":"ささえること",
  "threaten":"おどすこと",
  "abhor":"とっても きらいなこと",
  /* けいようし */
  "foolish":"おばかな こと",
  "specific":"とくべつな ひとつ",
  "available":"つかえる じょうたい",
  "rational":"おちついて かんがえられること",
  "ancient":"とても むかしの",
  "brief":"みじかい",
  "complex":"ふくざつな",
  "crucial":"とても たいせつな",
  "delicate":"こわれやすい・せんさいな",
  "efficient":"むだなく うまくできる",
  "enormous":"とても おおきい",
  "essential":"なくては ならない",
  "fluent":"ぺらぺら はなせる",
  "generous":"こころが ひろく やさしい",
  "intelligent":"あたまが いい",
  "mature":"おとなっぽい",
  "obvious":"みれば すぐ わかる",
  "permanent":"ずっと かわらない",
  "previous":"まえの",
  "reasonable":"なっとくできる・ちょうどいい",
  "reliable":"しんらいできる",
  "significant":"とても たいせつな",
  "sufficient":"じゅうぶんな",
  "temporary":"いっときだけの",
  "unique":"ほかにない めずらしい",
  /* めいし */
  "environment":"まわりの しぜん",
  "symmetry":"ひだりと みぎが おなじ かたち",
  "vehicle":"くるまなどの のりもの",
  "decision":"きめること",
  "benefit":"いいこと・とくになること",
  "advantage":"ゆうりな いいところ",
  "ability":"できる ちから",
  "attention":"しっかり みる・きく こと",
  "courage":"こわくても やる ゆうき",
  "culture":"そのくにの くらしや しゅうかん",
  "emotion":"うれしい・かなしい などの きもち",
  "generation":"おなじ じだいの ひとたち",
  "gravity":"ものを したに ひっぱる ちから",
  "habit":"いつもの くせ",
  "influence":"ほかに あたえる ちから",
  "knowledge":"しっていること",
  "opportunity":"いい チャンス",
  "population":"そこに すむ ひとの かず",
  "poverty":"とても まずしいこと",
  "purpose":"なんのために するか",
  "quality":"もののよさ",
  "quantity":"ものの かず・りょう",
  "relationship":"ひとと ひとの つながり",
  "responsibility":"じぶんが やるべき こと",
  "solution":"もんだいの こたえ",
  "strategy":"うまくいく ための さくせん",
  "tradition":"むかしから つづく やりかた",
  "wealth":"たくさんの おかね",
  /* === 英検3級 ついか === */
  "famous":"みんなが しっている",
  "popular":"にんきが ある",
  "expensive":"ねだんが たかい",
  "cheap":"ねだんが やすい",
  "enough":"もう じゅうぶん あること",
  "happen":"できごとが おきること",
  "invite":"きてね と さそうこと",
  "almost":"もうすこしで",
  "instead":"それの かわりに",
  "decide":"こうしよう と きめること",
  "nervous":"どきどき している",
  "important":"とても たいせつな",
  "remember":"わすれずに おぼえている・おもいだすこと",
  "arrive":"めざす ばしょに つくこと",
  "borrow":"かりること",
  "lend":"かしてあげること",
  "believe":"ほんとうだ と おもうこと",
  "should":"〜した ほうが いいよ ということ",
  "guess":"たぶん こうかな と かんがえること",
  "pay":"おかねを はらうこと",
  "save":"おかねを ためる・たすけること",
  "invent":"だれも しらない ものを はじめて つくること",
  "choose":"いくつかから えらぶこと",
  "promise":"かならず やると やくそくすること",
  "notice":"ふと きづくこと",
  "collect":"あつめること",
  "accident":"おもいがけない わるい できごと",
  "cost":"いくら かかるか",
  "keep":"もちつづける・たもつこと",
  "order":"おみせで ちゅうもんすること",
  "fun":"たのしいこと",
  "international":"いろんな くにに かんけいする",
  "boring":"つまらない",
  "amazing":"びっくりするほど すごい",
  "worry":"しんぱいすること",
  "award":"がんばった ごほうびの しょう",
  "prize":"がんばった ごほうびの しょう",
  "draw":"えを かくこと",
  "wrong":"まちがっている",
  "understand":"いみが わかること",
  "reason":"どうして？の わけ",
  "peaceful":"けんかが なく おだやかな",
  "thirsty":"のどが かわいている",
  "handle":"じょうずに あつかうこと",
  "hungry":"おなかが すいている",
  "nature":"やま・かわ・きなどの しぜん",
  "design":"かたちを かんがえて つくること",
  "receive":"うけとること",
  "injure":"けがを させること",
  "hurt":"けがを させる・いたくすること",
  "die":"いきものが しんでしまうこと",
  "pleasure":"うれしい たのしい きもち",
  "move":"うごく・ひっこしすること",
  "fix":"なおす・うごかないように とめること",
  "spend":"おかねや じかんを つかうこと",
  "taste":"たべものの あじ",
  "explain":"わかるように せつめいすること",
  "local":"その ちいきの",
  "steal":"ひとのものを こっそり とること",
  "rise":"たかく のぼること",
  "quick":"すばやい",
  "ever":"いままでに",
  "shape":"かたち",
  "company":"おしごとを する ところ",
  "history":"むかし あった できごと",
  "visitor":"あそびに きた ひと",
  "boil":"おゆで にること",
  "advice":"こうしたら いいよ という アドバイス",
  "piece":"ぜんたいの ひとかけら",
  "few":"すこしだけ",
  "same":"おなじ",
  "last":"いちばん おわり・ひとつ まえ",
  "headache":"あたまが いたいこと",
  "horror":"こわい こと",
  "difficult":"むずかしい",
  "healthy":"げんきで からだに いい",
  "strong":"ちからが つよい",
  "bright":"ひかって あかるい",
  "heavy":"おもい",
  "large":"とても おおきい",
  "wide":"はばが ひろい",
  "loud":"おとが おおきくて うるさい",
  "busy":"やることが おおくて いそがしい",
  "sick":"びょうきの",
  "sad":"かなしい",
  "angry":"おこっている",
  "glad":"うれしい",
  "dirty":"よごれている",
  "delicious":"とても おいしい",
  "favorite":"いちばん すきな",
  "excited":"わくわく している",
  "exciting":"わくわく させる",
  "interesting":"おもしろい",
  "convenient":"べんりな",
  "comfortable":"きもちよくて らくな",
  "dangerous":"あぶない",
  "useful":"やくに たつ",
  "simple":"かんたんな",
  "real":"ほんものの",
  "true":"ほんとうの",
  "special":"とくべつな",
  "main":"いちばん だいじな",
  /* 熟語・じゅくご */
  "look for":"さがすこと",
  "look forward to":"たのしみに まつこと",
  "take care of":"せわを すること",
  "pick up":"ひろいあげること",
  "turn on":"スイッチを いれること",
  "turn off":"スイッチを けすこと",
  "get off":"のりものから おりること",
  "run away":"にげること",
  "take part in":"さんかすること",
  "in fact":"じつは",
  "right away":"いますぐ",
  "get married":"けっこんすること",
  "be born":"うまれること",
  "think of":"おもいつくこと",
  "hurry up":"いそぐこと",
  "be afraid of":"〜が こわいこと",
  "be proud of":"〜を じまんに おもうこと",
  "be interested in":"〜に きょうみが あること",
  "be good at":"〜が じょうずなこと",
  "be kind to":"〜に やさしくすること",
  "agree with":"〜に さんせいすること",
  "look forward":"たのしみに まつこと",
  /* === 英検3級 ついか2 === */
  "teach":"おしえること",
  "memory":"おぼえていること・おもいで",
  "wish":"こうなったら いいなと ねがうこと",
  "answer":"しつもんに こたえること",
  "example":"「たとえば」の れい",
  "century":"100ねんの こと",
  "moment":"ほんの すこしの じかん",
  "difference":"ちがい",
  "finish":"おわらせること",
  "actually":"じつは",
  "noisy":"おとが うるさい",
  "recently":"さいきん",
  "fact":"ほんとうの こと",
  "reach":"てや ばしょに とどくこと",
  "lose":"なくす・まけること",
  "matter":"こまった もんだい",
  "forget":"わすれること",
  "rest":"やすむこと",
  "finally":"やっと さいごに",
  "cry":"なくこと",
  "grade":"せいせきの ひょうか",
  "kind":"しゅるい",
  "square":"しかくい かたち",
  "continue":"つづくこと",
  "abroad":"がいこく へ",
  "market":"しなものを うりかいする ところ",
  "health":"からだの ちょうし",
  "fresh":"とれたてで あたらしい",
  "build":"たてものを たてること",
  "future":"これからの みらい",
  "never":"いちども ないこと",
  "silent":"しずかで おとが ない",
  "several":"いくつかの",
  "foreign":"がいこくの",
  "interest":"きょうみ",
  "speak":"はなすこと",
  "correct":"ただしい・せいかい",
  "clever":"あたまが いい",
  "probably":"たぶん",
  "know":"しっていること",
  "exchange":"とりかえること",
  "shake":"ぶるぶる ゆれること",
  "raise":"てを あげる・もちあげること",
  "agree":"さんせいすること",
  "smell":"においが すること",
  "poor":"びんぼうな",
  "graduate":"がっこうを そつぎょうすること",
  "traditional":"むかしから つづく",
  "heaven":"てんごく",
  "fool":"おばかさん",
  "address":"いえの じゅうしょ",
  "lie":"うそ",
  "personal":"じぶん だけの",
  "gentle":"やさしくて おだやかな",
  "shout":"おおきな こえで さけぶこと",
  "ordinary":"ふつうの",
  "whole":"ぜんぶの",
  "calm":"おちついている",
  "fail":"しっぱいすること",
  "unhappy":"しあわせ じゃない",
  "violence":"らんぼうな こうい",
  "awesome":"すごく すばらしい",
  "enemy":"てき",
  "fight":"たたかうこと",
  "worth":"ねうちが ある",
  "custom":"その くにの しゅうかん",
  "illegal":"ほうりつ いはんの",
  "latest":"いちばん あたらしい",
  "hurry":"いそぐこと",
  "shelter":"ひなんする ばしょ",
  "crowd":"おおぜいの ひとの あつまり",
  "fill":"いっぱいに すること",
  "disagree":"いけんが あわないこと",
  "destroy":"こわすこと",
  "brain":"のうみそ・あたま",
  "border":"くにと くにの さかい",
  "death":"しんで しまうこと",
  "earth":"ちきゅう",
  "emergency":"きんきゅうの たいへんなとき",
  "earthquake":"じめんが ゆれる じしん",
  "laugh":"わらうこと",
  "tough":"たいへんで むずかしい",
  "president":"だいとうりょう・しゃちょう",
  "low":"ひくい",
  "branch":"きの えだ",
  "common":"みんなに きょうつうの",
  "discover":"あたらしく みつけること",
  "peace":"せんそうの ない へいわ",
  "wonder":"ふしぎだなと おもうこと",
  "war":"せんそう",
  "roof":"いえの やね",
  "tax":"みんなが はらう ぜいきん",
  "medicine":"びょうきを なおす くすり",
  "drop":"おちること",
  "absent":"がっこうなどを やすむこと",
  "possible":"できそうな こと",
  "introduce":"しょうかいすること",
  "ban":"やっては だめと きんしすること",
  "land":"つち・とち",
  "creative":"あたらしいものを つくる ちからが ある",
  "daily":"まいにちの",
  "hopeful":"きぼうが ある",
  "desert":"すなの さばく",
  "port":"ふねの みなと",
  "researcher":"けんきゅうする ひと",
  "belong":"〜の ものである",
  "electricity":"でんき",
  "establish":"あたらしく つくる・せつりつする",
  "climb":"たかいところに のぼること",
  "valley":"やまと やまの あいだの たに",
  "transport":"ものを はこぶこと",
  "blow":"かぜが ふくこと",
  "silk":"つるつるの きぬの ぬの",
  "shoulder":"かた",
  "national":"くにの",
  "survey":"みんなに きく ちょうさ",
  "sort":"しゅるい",
  "although":"〜だけれど",
  /* 熟語2 */
  "as usual":"いつものように",
  "in those days":"そのころは",
  "wait for":"〜を まつこと",
  "at first":"さいしょは",
  "a kind of":"いっしゅの",
  "not at all":"ぜんぜん 〜ない",
  "worry about":"〜を しんぱいすること",
  "at last":"やっと さいごに",
  "for free":"むりょうで・ただで",
  "less than":"〜より すくない",
  "go abroad":"がいこくへ いくこと",
  "as a result of":"〜の けっか",
  "in advance":"まえもって",
  "drop out":"とちゅうで やめること",
  "believe in":"〜を しんじること",
  "care for":"せわを すること",
  "from now on":"これからは",
  "run out of":"つかいきって なくなること",
  "most of":"〜の ほとんど",
  "in a hurry":"いそいで",
  "get out":"そとへ でること",
  "on the other hand":"いっぽうで",
  "according to":"〜に よると",
  "take out":"もちかえり",
  "on foot":"あるいて",
  "get on":"のりものに のること",
  "such as":"〜のような",
  "by bus":"バスで",
  "by car":"くるまで",
  "go straight":"まっすぐ いくこと",
  "eat out":"そとで ごはんを たべること",
  "learn about":"〜について まなぶこと"
};

Object.assign(EASY, {"weekend": "どようびと にちようび", "join": "なかまに はいること", "leave": "そのばしょを はなれること", "different": "ちがっている", "visit": "あいに・みに いくこと", "stay": "そのばしょに とどまること", "hope": "こうなったら いいなと ねがうこと", "together": "みんな いっしょに", "vacation": "ながい おやすみ", "need to": "〜する ひつようが ある", "sure": "ぜったい そうだと おもうこと", "break": "こわれる・こわすこと", "usually": "いつもは・ふだんは", "sign": "みちの ひょうしき", "how often": "どれくらい よく するか", "dictionary": "ことばの いみを しらべる ほん", "put": "ものを おくこと", "try on": "ふくを きてみること", "clock": "おく とけい", "again": "もう いちど", "cook": "りょうりを つくること", "get": "てに いれること", "information": "やくに たつ おしらせ", "season": "はる なつ あき ふゆ", "city hall": "まちの やくしょ", "on weekends": "どようび にちようびに", "museum": "めずらしいものを みる ところ", "try": "やってみること", "each other": "おたがいに", "customer": "おみせの おきゃくさん", "salt": "しょっぱい しろい こな", "late": "じかんに おくれている", "cold": "つめたい", "wash": "みずで あらうこと", "grandfather": "おじいちゃん", "husband": "おっと（だんなさん）", "turn": "まがる・まわること", "price": "もののねだん", "each": "ひとつ ひとつ", "hard": "いっしょうけんめい", "cloudy": "くもが おおい てんき", "through": "なかを とおりぬけて", "since": "〜から ずっと", "rule": "きまり・ルール", "in the future": "これから さきに", "rainy": "あめの てんき", "mirror": "すがたを うつす かがみ", "stay with": "〜と いっしょに すごすこと", "work for": "〜の ために はたらくこと", "hole": "あな", "joined": "なかまに はいった", "pick": "えらぶこと", "be different from": "〜とは ちがうこと", "vegetable": "やさい", "date": "なんがつ なんにち", "wife": "つま（おくさん）", "daughter": "むすめ", "side": "よこ・がわ", "hat": "ぼうし", "theater": "えいがや げきを みる ところ", "umbrella": "かさ", "art": "え や おんがくの げいじゅつ", "grandmother": "おばあちゃん", "airplane": "そらを とぶ ひこうき", "judge": "しんぱん する ひと", "toy": "おもちゃ", "behind": "うしろに", "outside": "そとがわに", "airline": "ひこうきの かいしゃ", "hill": "ちいさな やま（おか）", "quickly": "すばやく", "burn": "もやすこと", "very": "とても", "held": "てに もった", "lost": "なくした", "tell": "ことばで つたえること", "gave": "あげた", "walk": "さんぽ・あるくこと", "within": "〜いないで", "yesterday": "きのう", "beginning": "いちばん さいしょ", "in season": "いま よくとれる じき", "evacuation": "あぶないところから にげること", "independence": "じぶんの ちからで やっていくこと", "well": "げんきな", "bother": "めんどうを かけること", "surprisingly": "おどろいたことに", "on the way": "いく とちゅうで", "spelling": "ことばの つづり", "nuclear": "げんしりょくの", "palace": "おうさまの すむ おしろ", "bake": "オーブンで やくこと", "electronic device": "でんきで うごく きかい", "get fired": "しごとを やめさせられること", "sustainable": "ずっと つづけられる", "usual": "いつもの", "fossil fuel": "せきゆや せきたんの ねんりょう", "barber": "かみのけを きる おみせ", "just in case": "もしもの ときの ため", "from the experience": "やってみて わかったことから", "lip": "くちびる", "farewell party": "おわかれの パーティー", "relatively": "くらべると わりと", "not always": "いつも 〜とは かぎらない", "be excited": "わくわく すること", "on your right": "みぎがわに", "have a headache": "あたまが いたいこと", "agree to": "〜を いいよと みとめること", "definitely": "まちがいなく", "strict": "きびしい", "artistic": "げいじゅつ てきな", "in conclusion": "まとめると", "ecosystem": "いきものたちの つながり", "be in trouble": "こまっていること", "prefer A to B": "Bより Aの ほうが すきなこと", "with a smile": "にこにこ わらって", "functional": "じっさいに やくに たつ", "keep in touch": "れんらくを とりあうこと", "believe it or not": "しんじられないかも しれないけど", "endangered": "ぜつめつ しそうな", "breed": "どうぶつを そだてて ふやすこと", "wrap": "つつむこと", "lead": "せんとうで みちびくこと", "do a favor": "たのみごとを きいてあげること", "arrive at": "〜に つくこと", "jewel": "キラキラの ほうせき", "fall in love with": "〜を すきに なること", "be in danger of": "〜の きけんが あること", "government": "くにを うごかす せいふ", "countryside": "いなか", "amount": "りょう・かず", "limited": "かぎられた すくない", "climate": "その ちいきの てんきの ようす", "out of order": "こしょうして つかえない", "human rights": "ひとが もつ たいせつな けんり", "surround": "まわりを かこむこと", "holy": "かみさまの ような とうとい", "instruction": "やりかたの せつめい", "waste": "むだに つかうこと", "weekly": "しゅうに いっかいの", "on the wall": "かべに", "magazine": "ざっし", "store": "ためて おくこと", "lazy": "なまけものの", "discrimination": "ふこうへいな さべつ", "fold": "おりたたむこと", "afraid": "こわがって", "all over": "〜じゅう ぜんぶに", "steam": "ゆげ", "pain": "いたみ", "chemical": "かがくの ぶっしつ", "check out": "しらべること", "capture": "つかまえること", "paper crane": "おりがみの つる", "be concerned with": "〜に かんけいしていること", "wet": "ぬれている", "arrest": "けいさつが つかまえること", "curious": "しりたがりの", "encourage to ～": "〜するように おうえんすること", "unfair": "ずるくて こうへいでない", "strange": "へんな・ふしぎな", "tired": "つかれている", "take a rest": "やすむこと", "statue": "どうや いしの ぞう", "law": "まもるべき ほうりつ", "check ～ out": "〜を かくにんすること", "stationery shop": "ぶんぼうぐの おみせ", "search for": "さがすこと", "in detail": "こまかく くわしく", "growth": "ふえて おおきく なること", "stationery": "えんぴつや ノートの ぶんぼうぐ", "carbon dioxide": "はくいきに ある きたい(にさんかたんそ)", "hear from": "〜から れんらくが くること", "wake": "めが さめること", "depend on": "〜に たよること", "bomb": "ばくはつする ばくだん", "resident": "そこに すんでいる ひと", "audience": "みている おきゃくさん", "brave": "ゆうきが ある", "extinguisher": "ひを けす しょうかき", "be likely to": "〜しそうなこと", "trade": "くにと くにの ぼうえき", "hall": "ろうか・ひろい へや", "be in need of": "〜が ひつようなこと", "fill in": "ひつようなことを かきこむこと", "run": "おみせなどを やっていくこと", "flight": "ひこうきの びん", "get lost": "みちに まようこと", "renewable": "なんども つかえる", "all the time": "いつも ずっと", "ask someone for": "だれかに 〜を おねがいすること", "donate": "ただで あげる・きふすること", "nest": "とりの す", "import": "がいこくから かいいれること", "secret": "ひみつ", "given": "あたえられた", "unused": "まだ つかっていない", "debate": "テーマを きめて する とうろん", "note": "おさつ（おかね）", "awake": "めが さめている", "fall": "おちること", "crazy": "むちゃくちゃな", "for instance": "たとえば", "discussion": "はなしあい", "drop by": "ちょっと よること", "metal": "きんぞく", "relation": "かんけい", "colony": "べつの くにに しはいされた とち", "past": "むかしの", "succeed": "うまく いくこと", "certain": "まちがいない", "be amazed at": "〜に びっくりすること", "modern": "いまふうの", "get rid of": "いらないものを なくすこと", "affect": "〜に えいきょうを あたえること", "match": "しあい", "be satisfied with": "〜に まんぞくしていること", "quietly": "しずかに", "for example": "たとえば", "fall asleep": "ねむりに つくこと", "signal": "しんごう", "protest": "はんたいだと こうぎすること", "extinction": "いきものが いなくなる ぜつめつ", "belong to": "〜の ものであること", "pleased": "よろこんで", "uniform": "せいふく", "neighbor": "となりの ひと", "leg": "あし", "army": "りくぐん（ぐんたい）", "universe": "うちゅう", "effective": "こうかが ある", "pursue": "おいかけて もとめること", "step": "いっぽ・かいだん", "an average of": "へいきんで 〜", "relate to ～": "〜に かんけいさせること", "condition": "ようす・じょうたい", "burden": "おもい ふたん", "wood": "もくざい・き", "shade": "ひかげ", "quiet": "しずかな", "billion": "10おく", "graduation": "がっこうの そつぎょう", "heat": "あつい ねつ", "get tired": "つかれること", "successful": "せいこうした", "weapon": "たたかいの ぶき", "necessary": "どうしても ひつような", "someone in need": "たすけが ひつような ひと", "be scared of": "〜が こわいこと", "consumer": "ものを かう ひと", "depend": "たよること", "trust": "しんようすること", "film": "えいが", "loss": "なくすこと", "honey": "ハチの あまい みつ", "suddenly": "きゅうに", "disaster": "じしんなどの さいがい", "pass by": "よこを とおりすぎること", "charge": "でんきを ためること", "resource": "やくに たつ しげん", "police officer": "けいさつかん", "ashamed": "はずかしくて", "image": "え・イメージ", "be familiar with": "〜を よく しっていること", "planet": "ちきゅうのような わくせい", "exception": "ほかと ちがう れいがい", "certainly": "たしかに", "surely": "たしかに", "device": "きかい・どうぐ", "arm": "うで", "be responsible for": "〜の せきにんが あること", "treasure": "たからもの", "call back": "おりかえし でんわすること", "die out": "いなくなる・ぜつめつすること", "sit down": "すわること", "look after": "せわを すること", "mind": "こころ", "take it back": "とりもどすこと", "fly": "そらを とぶこと", "tear": "なみだ", "employee": "やとわれて はたらく ひと", "survival": "いきのこること", "species": "いきものの しゅるい", "lawyer": "ほうりつの せんもんか べんごし", "parking lot": "くるまを とめる ところ", "success": "せいこう", "try hard": "いっしょうけんめい やること", "himself": "かれ じしんを", "sleepy": "ねむい", "away": "はなれて", "dislike": "きらうこと", "excuse": "ゆるすこと", "Long time no see.": "ひさしぶり", "That's all right.": "だいじょうぶだよ", "I appreciate it.": "ありがとう、たすかるよ", "I owe you one.": "こんど おかえし するね", "Can I ask a question?": "しつもん して いい？", "Can I try it on?": "きてみても いい？", "May I borrow this book?": "この ほん かりても いい？", "Shall I help you?": "てつだおうか？", "Let me help you.": "てつだわせてね", "I'll call you back.": "あとで でんわ かけなおすね", "Tell me if you need anything.": "なにか いるなら いってね", "I'll be right back.": "すぐ もどるね", "Why don't you ask her?": "かのじょに きいてみたら？", "Let's take a break.": "ちょっと やすもう", "Shall we watch a movie?": "えいが みようか？", "Are you busy now?": "いま いそがしい？", "I'm ready to go.": "でかける じゅんび できたよ", "I'm running late.": "ちょっと おくれそう", "I forgot my homework.": "しゅくだいを わすれちゃった", "I need my dictionary.": "じしょが いるんだ", "Please hand in your report.": "レポートを だしてね", "I left school early.": "はやびけ したよ", "I have to study for the exam.": "テストの べんきょうを しなきゃ", "The class is over.": "じゅぎょうが おわったよ", "Could you help me with math?": "さんすう てつだってくれる？", "Can I help you?": "なにか おさがしですか", "Can I try this on?": "これ きてみても いい？", "I'm looking for a gift.": "プレゼントを さがしてるんだ", "Can you wrap it, please?": "つつんで もらえますか", "I'd like a salad, please.": "サラダを ください", "I'm ready to order.": "ちゅうもん できます", "No tomatoes, please.": "トマトは ぬいてください", "The food is delicious.": "りょうりが おいしい", "It's too spicy for me.": "わたしには からすぎる", "Could we have the bill?": "おかいけい おねがいします", "I'll have the same.": "おなじものを ください", "Save some for me.": "ちょっと のこしておいてね", "We missed the train.": "でんしゃに のりおくれた", "This seat is taken.": "この せきは あいてないよ", "I got off at the wrong station.": "ちがう えきで おりちゃった", "Please tell me when to get off.": "おりる とき おしえてね", "Take an umbrella with you.": "かさを もっていってね", "Spring is my favorite season.": "はるが いちばん すきな きせつ", "I love autumn leaves.": "こうようが だいすき", "I have a fever.": "ねつが あるんだ", "I have a headache.": "あたまが いたい", "I caught a cold.": "かぜを ひいちゃった", "My stomach hurts.": "おなかが いたい", "I need to see a doctor.": "おいしゃさんに みてもらわなきゃ", "Don't stay up late.": "よふかし しないでね", "I'm a little tired.": "ちょっと つかれた", "I like this one.": "これが すき", "I don't like spicy food.": "からい たべものは すきじゃない", "I agree with you.": "きみに さんせい", "I prefer tea to coffee.": "コーヒーより おちゃが すき", "This is my favorite song.": "これが いちばん すきな うた", "I'm interested in art.": "びじゅつに きょうみが ある", "That's too difficult for me.": "わたしには むずかしすぎる", "The game starts soon.": "しあいが もうすぐ はじまる", "We won the match.": "しあいに かったよ", "We lost by one point.": "1てんさで まけた", "I'm a little worried.": "ちょっと しんぱい", "Let's cheer for them.": "みんなを おうえんしよう", "That was a great game.": "すごい しあいだった", "Please leave a message.": "でんごんを のこしてね", "Can I speak to Ken?": "ケンさん いますか", "My phone is out of battery.": "ケータイの でんちが きれた", "Check your email, please.": "メールを みてね", "Sorry, wrong number.": "ごめん、ばんごう まちがえた", "Please call me back.": "おりかえし でんわしてね", "I lost my wallet.": "さいふを なくした", "I forgot my ticket.": "きっぷを わすれた", "I left it at home.": "いえに おいてきちゃった", "My shoes are wet.": "くつが ぬれてる", "I'm proud of you.": "きみを ほこりに おもうよ", "Keep trying.": "あきらめずに つづけて", "That's too bad.": "それは ざんねんだね", "I'll be back.": "もどってくるね", "I have an appointment.": "やくそくが あるんだ", "I need to make a copy.": "コピーを とらなきゃ", "I was stuck in traffic.": "じゅうたいに はまってた", "I'm on my break.": "いま きゅうけいちゅう", "This is my first time.": "これが はじめてなんだ", "It's my piece of cake.": "それは わたしの ケーキだよ"});

Object.assign(EASY, {"rose": "のぼった（あがった）", "hold": "てに もつ・にぎること"});
