/* やさしいいみ辞書（小学生向けの かんたんな ことば）。
   キー=英単語(小文字)。ここに無い語は アプリ側で ひらがな表示にフォールバック。
   随時 追加してOK。 */
const EASY = {
  /* どうし */
  "retire":"しごとを やめること",
  "breathe":"いきを すること",
  "improve":"もっと よくすること",
  "reduce":"へらすこと",
  "increase":"ふやすこと",
  "decrease":"へらすこと",
  "describe":"ことばで せつめいすること",
  "imagine":"あたまの なかで おもいうかべること",
  "achieve":"がんばって できるように なること",
  "prepare":"したくを すること",
  "protect":"まもること",
  "negotiate":"はなしあって きめること",
  "recommend":"いいよと すすめること",
  "respect":"あいてを たいせつに おもうこと",
  "suggest":"こうしたら？と いうこと",
  "realize":"ああそうか と きづくこと",
  "recognize":"みて だれ・なにか わかること",
  "require":"ぜったい ひつよう ということ",
  "provide":"よういして あげること",
  "produce":"つくりだすこと",
  "appreciate":"ありがたいと おもうこと",
  "apologize":"ごめんなさい と いうこと",
  "celebrate":"おいわいを すること",
  "complain":"ふまんを いうこと",
  "encourage":"がんばって！と おうえんすること",
  "expand":"おおきく ひろげること",
  "explore":"たんけんして しらべること",
  "hesitate":"どうしようか まよって ためらうこと",
  "maintain":"そのまま たもつこと",
  "observe":"よく みて しらべること",
  "participate":"いっしょに さんかすること",
  "persuade":"せっとくして なっとくさせること",
  "predict":"これから どうなるか いいあてること",
  "pretend":"〜の ふりを すること",
  "prevent":"おきないように ふせぐこと",
  "purchase":"おかねを はらって かうこと",
  "recover":"げんきに もどること",
  "remind":"おもいださせること",
  "replace":"べつのものと いれかえること",
  "represent":"だいひょうすること",
  "solve":"もんだいを とくこと",
  "struggle":"たいへんで がんばること",
  "survive":"いきのこること",
  "translate":"べつの ことばに なおすこと",
  "warn":"あぶないよ と しらせること",
  "admire":"すごいなと あこがれること",
  "afford":"おかねが あって かえること",
  "announce":"みんなに しらせること",
  "attend":"その ばしょに いくこと",
  "avoid":"ぶつからないように さけること",
  "behave":"おぎょうぎよく すること",
  "consider":"よく かんがえること",
  "contain":"なかに はいっていること",
  "demand":"つよく もとめること",
  "develop":"そだてて よくしていくこと",
  "discuss":"みんなで はなしあうこと",
  "distribute":"みんなに くばること",
  "estimate":"だいたい これくらい と よそうすること",
  "examine":"くわしく しらべること",
  "expect":"きっと こうなる と おもうこと",
  "express":"きもちを あらわすこと",
  "include":"なかに ふくむこと",
  "indicate":"これだよ と しめすこと",
  "inform":"しらせること",
  "inspire":"やるきを わかせること",
  "intend":"そうしよう と おもうこと",
  "invest":"おかねを つかって ふやそうとすること",
  "manage":"なんとか うまく やること",
  "measure":"ながさや おもさを はかること",
  "mention":"ちょっと いうこと",
  "obtain":"てに いれること",
  "operate":"きかいを うごかすこと",
  "organize":"きちんと まとめること",
  "perform":"みんなの まえで えんじること",
  "permit":"いいよ と ゆるすこと",
  "prove":"ほんとうだ と しめすこと",
  "publish":"ほんなどを だすこと",
  "react":"なにかに たいして うごくこと",
  "refuse":"いやだ と ことわること",
  "regret":"ああすれば よかった と おもうこと",
  "release":"そとに だす・はなすこと",
  "remove":"とりのぞくこと",
  "repair":"こわれたものを なおすこと",
  "respond":"へんじを すること",
  "reveal":"かくれていたものを みせること",
  "satisfy":"まんぞくさせること",
  "seek":"さがし もとめること",
  "select":"えらぶこと",
  "settle":"おちつく・かたづけること",
  "share":"みんなで わけあうこと",
  "spread":"ひろがること",
  "supply":"ひつようなものを あたえること",
  "support":"ささえること",
  "threaten":"おどすこと",
  "abhor":"とっても きらいなこと",
  /* けいようし */
  "foolish":"おばかな こと",
  "specific":"とくべつな ひとつ",
  "available":"つかえる じょうたい",
  "rational":"おちついて かんがえられること",
  "ancient":"とても むかしの",
  "brief":"みじかい",
  "complex":"ふくざつな",
  "crucial":"とても たいせつな",
  "delicate":"こわれやすい・せんさいな",
  "efficient":"むだなく うまくできる",
  "enormous":"とても おおきい",
  "essential":"なくては ならない",
  "fluent":"ぺらぺら はなせる",
  "generous":"こころが ひろく やさしい",
  "intelligent":"あたまが いい",
  "mature":"おとなっぽい",
  "obvious":"みれば すぐ わかる",
  "permanent":"ずっと かわらない",
  "previous":"まえの",
  "reasonable":"なっとくできる・ちょうどいい",
  "reliable":"しんらいできる",
  "significant":"とても たいせつな",
  "sufficient":"じゅうぶんな",
  "temporary":"いっときだけの",
  "unique":"ほかにない めずらしい",
  /* めいし */
  "environment":"まわりの しぜん",
  "symmetry":"ひだりと みぎが おなじ かたち",
  "vehicle":"くるまなどの のりもの",
  "decision":"きめること",
  "benefit":"いいこと・とくになること",
  "advantage":"ゆうりな いいところ",
  "ability":"できる ちから",
  "attention":"しっかり みる・きく こと",
  "courage":"こわくても やる ゆうき",
  "culture":"そのくにの くらしや しゅうかん",
  "emotion":"うれしい・かなしい などの きもち",
  "generation":"おなじ じだいの ひとたち",
  "gravity":"ものを したに ひっぱる ちから",
  "habit":"いつもの くせ",
  "influence":"ほかに あたえる ちから",
  "knowledge":"しっていること",
  "opportunity":"いい チャンス",
  "population":"そこに すむ ひとの かず",
  "poverty":"とても まずしいこと",
  "purpose":"なんのために するか",
  "quality":"もののよさ",
  "quantity":"ものの かず・りょう",
  "relationship":"ひとと ひとの つながり",
  "responsibility":"じぶんが やるべき こと",
  "solution":"もんだいの こたえ",
  "strategy":"うまくいく ための さくせん",
  "tradition":"むかしから つづく やりかた",
  "wealth":"たくさんの おかね",
  /* === 英検3級 ついか === */
  "famous":"みんなが しっている",
  "popular":"にんきが ある",
  "expensive":"ねだんが たかい",
  "cheap":"ねだんが やすい",
  "enough":"もう じゅうぶん あること",
  "happen":"できごとが おきること",
  "invite":"きてね と さそうこと",
  "almost":"もうすこしで",
  "instead":"それの かわりに",
  "decide":"こうしよう と きめること",
  "nervous":"どきどき している",
  "important":"とても たいせつな",
  "remember":"わすれずに おぼえている・おもいだすこと",
  "arrive":"めざす ばしょに つくこと",
  "borrow":"かりること",
  "lend":"かしてあげること",
  "believe":"ほんとうだ と おもうこと",
  "should":"〜した ほうが いいよ ということ",
  "guess":"たぶん こうかな と かんがえること",
  "pay":"おかねを はらうこと",
  "save":"おかねを ためる・たすけること",
  "invent":"だれも しらない ものを はじめて つくること",
  "choose":"いくつかから えらぶこと",
  "promise":"かならず やると やくそくすること",
  "notice":"ふと きづくこと",
  "collect":"あつめること",
  "accident":"おもいがけない わるい できごと",
  "cost":"いくら かかるか",
  "keep":"もちつづける・たもつこと",
  "order":"おみせで ちゅうもんすること",
  "fun":"たのしいこと",
  "international":"いろんな くにに かんけいする",
  "boring":"つまらない",
  "amazing":"びっくりするほど すごい",
  "worry":"しんぱいすること",
  "award":"がんばった ごほうびの しょう",
  "prize":"がんばった ごほうびの しょう",
  "draw":"えを かくこと",
  "wrong":"まちがっている",
  "understand":"いみが わかること",
  "reason":"どうして？の わけ",
  "peaceful":"けんかが なく おだやかな",
  "thirsty":"のどが かわいている",
  "handle":"じょうずに あつかうこと",
  "hungry":"おなかが すいている",
  "nature":"やま・かわ・きなどの しぜん",
  "design":"かたちを かんがえて つくること",
  "receive":"うけとること",
  "injure":"けがを させること",
  "hurt":"けがを させる・いたくすること",
  "die":"いきものが しんでしまうこと",
  "pleasure":"うれしい たのしい きもち",
  "move":"うごく・ひっこしすること",
  "fix":"なおす・うごかないように とめること",
  "spend":"おかねや じかんを つかうこと",
  "taste":"たべものの あじ",
  "explain":"わかるように せつめいすること",
  "local":"その ちいきの",
  "steal":"ひとのものを こっそり とること",
  "rise":"たかく のぼること",
  "quick":"すばやい",
  "ever":"いままでに",
  "shape":"かたち",
  "company":"おしごとを する ところ",
  "history":"むかし あった できごと",
  "visitor":"あそびに きた ひと",
  "boil":"おゆで にること",
  "advice":"こうしたら いいよ という アドバイス",
  "piece":"ぜんたいの ひとかけら",
  "few":"すこしだけ",
  "same":"おなじ",
  "last":"いちばん おわり・ひとつ まえ",
  "headache":"あたまが いたいこと",
  "horror":"こわい こと",
  "difficult":"むずかしい",
  "healthy":"げんきで からだに いい",
  "strong":"ちからが つよい",
  "bright":"ひかって あかるい",
  "heavy":"おもい",
  "large":"とても おおきい",
  "wide":"はばが ひろい",
  "loud":"おとが おおきくて うるさい",
  "busy":"やることが おおくて いそがしい",
  "sick":"びょうきの",
  "sad":"かなしい",
  "angry":"おこっている",
  "glad":"うれしい",
  "dirty":"よごれている",
  "delicious":"とても おいしい",
  "favorite":"いちばん すきな",
  "excited":"わくわく している",
  "exciting":"わくわく させる",
  "interesting":"おもしろい",
  "convenient":"べんりな",
  "comfortable":"きもちよくて らくな",
  "dangerous":"あぶない",
  "useful":"やくに たつ",
  "simple":"かんたんな",
  "real":"ほんものの",
  "true":"ほんとうの",
  "special":"とくべつな",
  "main":"いちばん だいじな",
  /* 熟語・じゅくご */
  "look for":"さがすこと",
  "look forward to":"たのしみに まつこと",
  "take care of":"せわを すること",
  "pick up":"ひろいあげること",
  "turn on":"スイッチを いれること",
  "turn off":"スイッチを けすこと",
  "get off":"のりものから おりること",
  "run away":"にげること",
  "take part in":"さんかすること",
  "in fact":"じつは",
  "right away":"いますぐ",
  "get married":"けっこんすること",
  "be born":"うまれること",
  "think of":"おもいつくこと",
  "hurry up":"いそぐこと",
  "be afraid of":"〜が こわいこと",
  "be proud of":"〜を じまんに おもうこと",
  "be interested in":"〜に きょうみが あること",
  "be good at":"〜が じょうずなこと",
  "be kind to":"〜に やさしくすること",
  "agree with":"〜に さんせいすること",
  "look forward":"たのしみに まつこと",
  /* === 英検3級 ついか2 === */
  "teach":"おしえること",
  "memory":"おぼえていること・おもいで",
  "wish":"こうなったら いいなと ねがうこと",
  "answer":"しつもんに こたえること",
  "example":"「たとえば」の れい",
  "century":"100ねんの こと",
  "moment":"ほんの すこしの じかん",
  "difference":"ちがい",
  "finish":"おわらせること",
  "actually":"じつは",
  "noisy":"おとが うるさい",
  "recently":"さいきん",
  "fact":"ほんとうの こと",
  "reach":"てや ばしょに とどくこと",
  "lose":"なくす・まけること",
  "matter":"こまった もんだい",
  "forget":"わすれること",
  "rest":"やすむこと",
  "finally":"やっと さいごに",
  "cry":"なくこと",
  "grade":"せいせきの ひょうか",
  "kind":"しゅるい",
  "square":"しかくい かたち",
  "continue":"つづくこと",
  "abroad":"がいこく へ",
  "market":"しなものを うりかいする ところ",
  "health":"からだの ちょうし",
  "fresh":"とれたてで あたらしい",
  "build":"たてものを たてること",
  "future":"これからの みらい",
  "never":"いちども ないこと",
  "silent":"しずかで おとが ない",
  "several":"いくつかの",
  "foreign":"がいこくの",
  "interest":"きょうみ",
  "speak":"はなすこと",
  "correct":"ただしい・せいかい",
  "clever":"あたまが いい",
  "probably":"たぶん",
  "know":"しっていること",
  "exchange":"とりかえること",
  "shake":"ぶるぶる ゆれること",
  "raise":"てを あげる・もちあげること",
  "agree":"さんせいすること",
  "smell":"においが すること",
  "poor":"びんぼうな",
  "graduate":"がっこうを そつぎょうすること",
  "traditional":"むかしから つづく",
  "heaven":"てんごく",
  "fool":"おばかさん",
  "address":"いえの じゅうしょ",
  "lie":"うそ",
  "personal":"じぶん だけの",
  "gentle":"やさしくて おだやかな",
  "shout":"おおきな こえで さけぶこと",
  "ordinary":"ふつうの",
  "whole":"ぜんぶの",
  "calm":"おちついている",
  "fail":"しっぱいすること",
  "unhappy":"しあわせ じゃない",
  "violence":"らんぼうな こうい",
  "awesome":"すごく すばらしい",
  "enemy":"てき",
  "fight":"たたかうこと",
  "worth":"ねうちが ある",
  "custom":"その くにの しゅうかん",
  "illegal":"ほうりつ いはんの",
  "latest":"いちばん あたらしい",
  "hurry":"いそぐこと",
  "shelter":"ひなんする ばしょ",
  "crowd":"おおぜいの ひとの あつまり",
  "fill":"いっぱいに すること",
  "disagree":"いけんが あわないこと",
  "destroy":"こわすこと",
  "brain":"のうみそ・あたま",
  "border":"くにと くにの さかい",
  "death":"しんで しまうこと",
  "earth":"ちきゅう",
  "emergency":"きんきゅうの たいへんなとき",
  "earthquake":"じめんが ゆれる じしん",
  "laugh":"わらうこと",
  "tough":"たいへんで むずかしい",
  "president":"だいとうりょう・しゃちょう",
  "low":"ひくい",
  "branch":"きの えだ",
  "common":"みんなに きょうつうの",
  "discover":"あたらしく みつけること",
  "peace":"せんそうの ない へいわ",
  "wonder":"ふしぎだなと おもうこと",
  "war":"せんそう",
  "roof":"いえの やね",
  "tax":"みんなが はらう ぜいきん",
  "medicine":"びょうきを なおす くすり",
  "drop":"おちること",
  "absent":"がっこうなどを やすむこと",
  "possible":"できそうな こと",
  "introduce":"しょうかいすること",
  "ban":"やっては だめと きんしすること",
  "land":"つち・とち",
  "creative":"あたらしいものを つくる ちからが ある",
  "daily":"まいにちの",
  "hopeful":"きぼうが ある",
  "desert":"すなの さばく",
  "port":"ふねの みなと",
  "researcher":"けんきゅうする ひと",
  "belong":"〜の ものである",
  "electricity":"でんき",
  "establish":"あたらしく つくる・せつりつする",
  "climb":"たかいところに のぼること",
  "valley":"やまと やまの あいだの たに",
  "transport":"ものを はこぶこと",
  "blow":"かぜが ふくこと",
  "silk":"つるつるの きぬの ぬの",
  "shoulder":"かた",
  "national":"くにの",
  "survey":"みんなに きく ちょうさ",
  "sort":"しゅるい",
  "although":"〜だけれど",
  /* 熟語2 */
  "as usual":"いつものように",
  "in those days":"そのころは",
  "wait for":"〜を まつこと",
  "at first":"さいしょは",
  "a kind of":"いっしゅの",
  "not at all":"ぜんぜん 〜ない",
  "worry about":"〜を しんぱいすること",
  "at last":"やっと さいごに",
  "for free":"むりょうで・ただで",
  "less than":"〜より すくない",
  "go abroad":"がいこくへ いくこと",
  "as a result of":"〜の けっか",
  "in advance":"まえもって",
  "drop out":"とちゅうで やめること",
  "believe in":"〜を しんじること",
  "care for":"せわを すること",
  "from now on":"これからは",
  "run out of":"つかいきって なくなること",
  "most of":"〜の ほとんど",
  "in a hurry":"いそいで",
  "get out":"そとへ でること",
  "on the other hand":"いっぽうで",
  "according to":"〜に よると",
  "take out":"もちかえり",
  "on foot":"あるいて",
  "get on":"のりものに のること",
  "such as":"〜のような",
  "by bus":"バスで",
  "by car":"くるまで",
  "go straight":"まっすぐ いくこと",
  "eat out":"そとで ごはんを たべること",
  "learn about":"〜について まなぶこと"
};
