/* やさしいいみ辞書（小学生向けの かんたんな ことば）。
   キー=英単語(小文字)。ここに無い語は アプリ側で ひらがな表示にフォールバック。
   随時 追加してOK。 */
const EASY = {
  /* どうし */
  "retire":"しごとを やめること",
  "breathe":"いきを すること",
  "improve":"もっと よくすること",
  "reduce":"へらすこと",
  "increase":"ふやすこと",
  "decrease":"へらすこと",
  "describe":"ことばで せつめいすること",
  "imagine":"あたまの なかで おもいうかべること",
  "achieve":"がんばって できるように なること",
  "prepare":"したくを すること",
  "protect":"まもること",
  "negotiate":"はなしあって きめること",
  "recommend":"いいよと すすめること",
  "respect":"あいてを たいせつに おもうこと",
  "suggest":"こうしたら？と いうこと",
  "realize":"ああそうか と きづくこと",
  "recognize":"みて だれ・なにか わかること",
  "require":"ぜったい ひつよう ということ",
  "provide":"よういして あげること",
  "produce":"つくりだすこと",
  "appreciate":"ありがたいと おもうこと",
  "apologize":"ごめんなさい と いうこと",
  "celebrate":"おいわいを すること",
  "complain":"ふまんを いうこと",
  "encourage":"がんばって！と おうえんすること",
  "expand":"おおきく ひろげること",
  "explore":"たんけんして しらべること",
  "hesitate":"どうしようか まよって ためらうこと",
  "maintain":"そのまま たもつこと",
  "observe":"よく みて しらべること",
  "participate":"いっしょに さんかすること",
  "persuade":"せっとくして なっとくさせること",
  "predict":"これから どうなるか いいあてること",
  "pretend":"〜の ふりを すること",
  "prevent":"おきないように ふせぐこと",
  "purchase":"おかねを はらって かうこと",
  "recover":"げんきに もどること",
  "remind":"おもいださせること",
  "replace":"べつのものと いれかえること",
  "represent":"だいひょうすること",
  "solve":"もんだいを とくこと",
  "struggle":"たいへんで がんばること",
  "survive":"いきのこること",
  "translate":"べつの ことばに なおすこと",
  "warn":"あぶないよ と しらせること",
  "admire":"すごいなと あこがれること",
  "afford":"おかねが あって かえること",
  "announce":"みんなに しらせること",
  "attend":"その ばしょに いくこと",
  "avoid":"ぶつからないように さけること",
  "behave":"おぎょうぎよく すること",
  "consider":"よく かんがえること",
  "contain":"なかに はいっていること",
  "demand":"つよく もとめること",
  "develop":"そだてて よくしていくこと",
  "discuss":"みんなで はなしあうこと",
  "distribute":"みんなに くばること",
  "estimate":"だいたい これくらい と よそうすること",
  "examine":"くわしく しらべること",
  "expect":"きっと こうなる と おもうこと",
  "express":"きもちを あらわすこと",
  "include":"なかに ふくむこと",
  "indicate":"これだよ と しめすこと",
  "inform":"しらせること",
  "inspire":"やるきを わかせること",
  "intend":"そうしよう と おもうこと",
  "invest":"おかねを つかって ふやそうとすること",
  "manage":"なんとか うまく やること",
  "measure":"ながさや おもさを はかること",
  "mention":"ちょっと いうこと",
  "obtain":"てに いれること",
  "operate":"きかいを うごかすこと",
  "organize":"きちんと まとめること",
  "perform":"みんなの まえで えんじること",
  "permit":"いいよ と ゆるすこと",
  "prove":"ほんとうだ と しめすこと",
  "publish":"ほんなどを だすこと",
  "react":"なにかに たいして うごくこと",
  "refuse":"いやだ と ことわること",
  "regret":"ああすれば よかった と おもうこと",
  "release":"そとに だす・はなすこと",
  "remove":"とりのぞくこと",
  "repair":"こわれたものを なおすこと",
  "respond":"へんじを すること",
  "reveal":"かくれていたものを みせること",
  "satisfy":"まんぞくさせること",
  "seek":"さがし もとめること",
  "select":"えらぶこと",
  "settle":"おちつく・かたづけること",
  "share":"みんなで わけあうこと",
  "spread":"ひろがること",
  "supply":"ひつようなものを あたえること",
  "support":"ささえること",
  "threaten":"おどすこと",
  "abhor":"とっても きらいなこと",
  /* けいようし */
  "foolish":"おばかな こと",
  "specific":"とくべつな ひとつ",
  "available":"つかえる じょうたい",
  "rational":"おちついて かんがえられること",
  "ancient":"とても むかしの",
  "brief":"みじかい",
  "complex":"ふくざつな",
  "crucial":"とても たいせつな",
  "delicate":"こわれやすい・せんさいな",
  "efficient":"むだなく うまくできる",
  "enormous":"とても おおきい",
  "essential":"なくては ならない",
  "fluent":"ぺらぺら はなせる",
  "generous":"こころが ひろく やさしい",
  "intelligent":"あたまが いい",
  "mature":"おとなっぽい",
  "obvious":"みれば すぐ わかる",
  "permanent":"ずっと かわらない",
  "previous":"まえの",
  "reasonable":"なっとくできる・ちょうどいい",
  "reliable":"しんらいできる",
  "significant":"とても たいせつな",
  "sufficient":"じゅうぶんな",
  "temporary":"いっときだけの",
  "unique":"ほかにない めずらしい",
  /* めいし */
  "environment":"まわりの しぜん",
  "symmetry":"ひだりと みぎが おなじ かたち",
  "vehicle":"くるまなどの のりもの",
  "decision":"きめること",
  "benefit":"いいこと・とくになること",
  "advantage":"ゆうりな いいところ",
  "ability":"できる ちから",
  "attention":"しっかり みる・きく こと",
  "courage":"こわくても やる ゆうき",
  "culture":"そのくにの くらしや しゅうかん",
  "emotion":"うれしい・かなしい などの きもち",
  "generation":"おなじ じだいの ひとたち",
  "gravity":"ものを したに ひっぱる ちから",
  "habit":"いつもの くせ",
  "influence":"ほかに あたえる ちから",
  "knowledge":"しっていること",
  "opportunity":"いい チャンス",
  "population":"そこに すむ ひとの かず",
  "poverty":"とても まずしいこと",
  "purpose":"なんのために するか",
  "quality":"もののよさ",
  "quantity":"ものの かず・りょう",
  "relationship":"ひとと ひとの つながり",
  "responsibility":"じぶんが やるべき こと",
  "solution":"もんだいの こたえ",
  "strategy":"うまくいく ための さくせん",
  "tradition":"むかしから つづく やりかた",
  "wealth":"たくさんの おかね",
  /* === 英検3級 ついか === */
  "famous":"みんなが しっている",
  "popular":"にんきが ある",
  "expensive":"ねだんが たかい",
  "cheap":"ねだんが やすい",
  "enough":"もう じゅうぶん あること",
  "happen":"できごとが おきること",
  "invite":"きてね と さそうこと",
  "almost":"もうすこしで",
  "instead":"それの かわりに",
  "decide":"こうしよう と きめること",
  "nervous":"どきどき している",
  "important":"とても たいせつな",
  "remember":"わすれずに おぼえている・おもいだすこと",
  "arrive":"めざす ばしょに つくこと",
  "borrow":"かりること",
  "lend":"かしてあげること",
  "believe":"ほんとうだ と おもうこと",
  "should":"〜した ほうが いいよ ということ",
  "guess":"たぶん こうかな と かんがえること",
  "pay":"おかねを はらうこと",
  "save":"おかねを ためる・たすけること",
  "invent":"だれも しらない ものを はじめて つくること",
  "choose":"いくつかから えらぶこと",
  "promise":"かならず やると やくそくすること",
  "notice":"ふと きづくこと",
  "collect":"あつめること",
  "accident":"おもいがけない わるい できごと",
  "cost":"いくら かかるか",
  "keep":"もちつづける・たもつこと",
  "order":"おみせで ちゅうもんすること",
  "fun":"たのしいこと",
  "international":"いろんな くにに かんけいする",
  "boring":"つまらない",
  "amazing":"びっくりするほど すごい",
  "worry":"しんぱいすること",
  "award":"がんばった ごほうびの しょう",
  "prize":"がんばった ごほうびの しょう",
  "draw":"えを かくこと",
  "wrong":"まちがっている",
  "understand":"いみが わかること",
  "reason":"どうして？の わけ",
  "peaceful":"けんかが なく おだやかな",
  "thirsty":"のどが かわいている",
  "handle":"じょうずに あつかうこと",
  "hungry":"おなかが すいている",
  "nature":"やま・かわ・きなどの しぜん",
  "design":"かたちを かんがえて つくること",
  "receive":"うけとること",
  "injure":"けがを させること",
  "hurt":"けがを させる・いたくすること",
  "die":"いきものが しんでしまうこと",
  "pleasure":"うれしい たのしい きもち",
  "move":"うごく・ひっこしすること",
  "fix":"なおす・うごかないように とめること",
  "spend":"おかねや じかんを つかうこと",
  "taste":"たべものの あじ",
  "explain":"わかるように せつめいすること",
  "local":"その ちいきの",
  "steal":"ひとのものを こっそり とること",
  "rise":"たかく のぼること",
  "quick":"すばやい",
  "ever":"いままでに",
  "shape":"かたち",
  "company":"おしごとを する ところ",
  "history":"むかし あった できごと",
  "visitor":"あそびに きた ひと",
  "boil":"おゆで にること",
  "advice":"こうしたら いいよ という アドバイス",
  "piece":"ぜんたいの ひとかけら",
  "few":"すこしだけ",
  "same":"おなじ",
  "last":"いちばん おわり・ひとつ まえ",
  "headache":"あたまが いたいこと",
  "horror":"こわい こと",
  "difficult":"むずかしい",
  "healthy":"げんきで からだに いい",
  "strong":"ちからが つよい",
  "bright":"ひかって あかるい",
  "heavy":"おもい",
  "large":"とても おおきい",
  "wide":"はばが ひろい",
  "loud":"おとが おおきくて うるさい",
  "busy":"やることが おおくて いそがしい",
  "sick":"びょうきの",
  "sad":"かなしい",
  "angry":"おこっている",
  "glad":"うれしい",
  "dirty":"よごれている",
  "delicious":"とても おいしい",
  "favorite":"いちばん すきな",
  "excited":"わくわく している",
  "exciting":"わくわく させる",
  "interesting":"おもしろい",
  "convenient":"べんりな",
  "comfortable":"きもちよくて らくな",
  "dangerous":"あぶない",
  "useful":"やくに たつ",
  "simple":"かんたんな",
  "real":"ほんものの",
  "true":"ほんとうの",
  "special":"とくべつな",
  "main":"いちばん だいじな",
  /* 熟語・じゅくご */
  "look for":"さがすこと",
  "look forward to":"たのしみに まつこと",
  "take care of":"せわを すること",
  "pick up":"ひろいあげること",
  "turn on":"スイッチを いれること",
  "turn off":"スイッチを けすこと",
  "get off":"のりものから おりること",
  "run away":"にげること",
  "take part in":"さんかすること",
  "in fact":"じつは",
  "right away":"いますぐ",
  "get married":"けっこんすること",
  "be born":"うまれること",
  "think of":"おもいつくこと",
  "hurry up":"いそぐこと",
  "be afraid of":"〜が こわいこと",
  "be proud of":"〜を じまんに おもうこと",
  "be interested in":"〜に きょうみが あること",
  "be good at":"〜が じょうずなこと",
  "be kind to":"〜に やさしくすること",
  "agree with":"〜に さんせいすること",
  "look forward":"たのしみに まつこと",
  /* === 英検3級 ついか2 === */
  "teach":"おしえること",
  "memory":"おぼえていること・おもいで",
  "wish":"こうなったら いいなと ねがうこと",
  "answer":"しつもんに こたえること",
  "example":"「たとえば」の れい",
  "century":"100ねんの こと",
  "moment":"ほんの すこしの じかん",
  "difference":"ちがい",
  "finish":"おわらせること",
  "actually":"じつは",
  "noisy":"おとが うるさい",
  "recently":"さいきん",
  "fact":"ほんとうの こと",
  "reach":"てや ばしょに とどくこと",
  "lose":"なくす・まけること",
  "matter":"こまった もんだい",
  "forget":"わすれること",
  "rest":"やすむこと",
  "finally":"やっと さいごに",
  "cry":"なくこと",
  "grade":"せいせきの ひょうか",
  "kind":"しゅるい",
  "square":"しかくい かたち",
  "continue":"つづくこと",
  "abroad":"がいこく へ",
  "market":"しなものを うりかいする ところ",
  "health":"からだの ちょうし",
  "fresh":"とれたてで あたらしい",
  "build":"たてものを たてること",
  "future":"これからの みらい",
  "never":"いちども ないこと",
  "silent":"しずかで おとが ない",
  "several":"いくつかの",
  "foreign":"がいこくの",
  "interest":"きょうみ",
  "speak":"はなすこと",
  "correct":"ただしい・せいかい",
  "clever":"あたまが いい",
  "probably":"たぶん",
  "know":"しっていること",
  "exchange":"とりかえること",
  "shake":"ぶるぶる ゆれること",
  "raise":"てを あげる・もちあげること",
  "agree":"さんせいすること",
  "smell":"においが すること",
  "poor":"びんぼうな",
  "graduate":"がっこうを そつぎょうすること",
  "traditional":"むかしから つづく",
  "heaven":"てんごく",
  "fool":"おばかさん",
  "address":"いえの じゅうしょ",
  "lie":"うそ",
  "personal":"じぶん だけの",
  "gentle":"やさしくて おだやかな",
  "shout":"おおきな こえで さけぶこと",
  "ordinary":"ふつうの",
  "whole":"ぜんぶの",
  "calm":"おちついている",
  "fail":"しっぱいすること",
  "unhappy":"しあわせ じゃない",
  "violence":"らんぼうな こうい",
  "awesome":"すごく すばらしい",
  "enemy":"てき",
  "fight":"たたかうこと",
  "worth":"ねうちが ある",
  "custom":"その くにの しゅうかん",
  "illegal":"ほうりつ いはんの",
  "latest":"いちばん あたらしい",
  "hurry":"いそぐこと",
  "shelter":"ひなんする ばしょ",
  "crowd":"おおぜいの ひとの あつまり",
  "fill":"いっぱいに すること",
  "disagree":"いけんが あわないこと",
  "destroy":"こわすこと",
  "brain":"のうみそ・あたま",
  "border":"くにと くにの さかい",
  "death":"しんで しまうこと",
  "earth":"ちきゅう",
  "emergency":"きんきゅうの たいへんなとき",
  "earthquake":"じめんが ゆれる じしん",
  "laugh":"わらうこと",
  "tough":"たいへんで むずかしい",
  "president":"だいとうりょう・しゃちょう",
  "low":"ひくい",
  "branch":"きの えだ",
  "common":"みんなに きょうつうの",
  "discover":"あたらしく みつけること",
  "peace":"せんそうの ない へいわ",
  "wonder":"ふしぎだなと おもうこと",
  "war":"せんそう",
  "roof":"いえの やね",
  "tax":"みんなが はらう ぜいきん",
  "medicine":"びょうきを なおす くすり",
  "drop":"おちること",
  "absent":"がっこうなどを やすむこと",
  "possible":"できそうな こと",
  "introduce":"しょうかいすること",
  "ban":"やっては だめと きんしすること",
  "land":"つち・とち",
  "creative":"あたらしいものを つくる ちからが ある",
  "daily":"まいにちの",
  "hopeful":"きぼうが ある",
  "desert":"すなの さばく",
  "port":"ふねの みなと",
  "researcher":"けんきゅうする ひと",
  "belong":"〜の ものである",
  "electricity":"でんき",
  "establish":"あたらしく つくる・せつりつする",
  "climb":"たかいところに のぼること",
  "valley":"やまと やまの あいだの たに",
  "transport":"ものを はこぶこと",
  "blow":"かぜが ふくこと",
  "silk":"つるつるの きぬの ぬの",
  "shoulder":"かた",
  "national":"くにの",
  "survey":"みんなに きく ちょうさ",
  "sort":"しゅるい",
  "although":"〜だけれど",
  /* 熟語2 */
  "as usual":"いつものように",
  "in those days":"そのころは",
  "wait for":"〜を まつこと",
  "at first":"さいしょは",
  "a kind of":"いっしゅの",
  "not at all":"ぜんぜん 〜ない",
  "worry about":"〜を しんぱいすること",
  "at last":"やっと さいごに",
  "for free":"むりょうで・ただで",
  "less than":"〜より すくない",
  "go abroad":"がいこくへ いくこと",
  "as a result of":"〜の けっか",
  "in advance":"まえもって",
  "drop out":"とちゅうで やめること",
  "believe in":"〜を しんじること",
  "care for":"せわを すること",
  "from now on":"これからは",
  "run out of":"つかいきって なくなること",
  "most of":"〜の ほとんど",
  "in a hurry":"いそいで",
  "get out":"そとへ でること",
  "on the other hand":"いっぽうで",
  "according to":"〜に よると",
  "take out":"もちかえり",
  "on foot":"あるいて",
  "get on":"のりものに のること",
  "such as":"〜のような",
  "by bus":"バスで",
  "by car":"くるまで",
  "go straight":"まっすぐ いくこと",
  "eat out":"そとで ごはんを たべること",
  "learn about":"〜について まなぶこと"
};

Object.assign(EASY, {"weekend": "どようびと にちようび", "join": "なかまに はいること", "leave": "そのばしょを はなれること", "different": "ちがっている", "visit": "あいに・みに いくこと", "stay": "そのばしょに とどまること", "hope": "こうなったら いいなと ねがうこと", "together": "みんな いっしょに", "vacation": "ながい おやすみ", "need to": "〜する ひつようが ある", "sure": "ぜったい そうだと おもうこと", "break": "こわれる・こわすこと", "usually": "いつもは・ふだんは", "sign": "みちの ひょうしき", "how often": "どれくらい よく するか", "dictionary": "ことばの いみを しらべる ほん", "put": "ものを おくこと", "try on": "ふくを きてみること", "clock": "おく とけい", "again": "もう いちど", "cook": "りょうりを つくること", "get": "てに いれること", "information": "やくに たつ おしらせ", "season": "はる なつ あき ふゆ", "city hall": "まちの やくしょ", "on weekends": "どようび にちようびに", "museum": "めずらしいものを みる ところ", "try": "やってみること", "each other": "おたがいに", "customer": "おみせの おきゃくさん", "salt": "しょっぱい しろい こな", "late": "じかんに おくれている", "cold": "つめたい", "wash": "みずで あらうこと", "grandfather": "おじいちゃん", "husband": "おっと（だんなさん）", "turn": "まがる・まわること", "price": "もののねだん", "each": "ひとつ ひとつ", "hard": "いっしょうけんめい", "cloudy": "くもが おおい てんき", "through": "なかを とおりぬけて", "since": "〜から ずっと", "rule": "きまり・ルール", "in the future": "これから さきに", "rainy": "あめの てんき", "mirror": "すがたを うつす かがみ", "stay with": "〜と いっしょに すごすこと", "work for": "〜の ために はたらくこと", "hole": "あな", "joined": "なかまに はいった", "pick": "えらぶこと", "be different from": "〜とは ちがうこと", "vegetable": "やさい", "date": "なんがつ なんにち", "wife": "つま（おくさん）", "daughter": "むすめ", "side": "よこ・がわ", "hat": "ぼうし", "theater": "えいがや げきを みる ところ", "umbrella": "かさ", "art": "え や おんがくの げいじゅつ", "grandmother": "おばあちゃん", "airplane": "そらを とぶ ひこうき", "judge": "しんぱん する ひと", "toy": "おもちゃ", "behind": "うしろに", "outside": "そとがわに", "airline": "ひこうきの かいしゃ", "hill": "ちいさな やま（おか）", "quickly": "すばやく", "burn": "もやすこと", "very": "とても", "held": "てに もった", "lost": "なくした", "tell": "ことばで つたえること", "gave": "あげた", "walk": "さんぽ・あるくこと", "within": "〜いないで", "yesterday": "きのう", "beginning": "いちばん さいしょ", "in season": "いま よくとれる じき", "evacuation": "あぶないところから にげること", "independence": "じぶんの ちからで やっていくこと", "well": "げんきな", "bother": "めんどうを かけること", "surprisingly": "おどろいたことに", "on the way": "いく とちゅうで", "spelling": "ことばの つづり", "nuclear": "げんしりょくの", "palace": "おうさまの すむ おしろ", "bake": "オーブンで やくこと", "electronic device": "でんきで うごく きかい", "get fired": "しごとを やめさせられること", "sustainable": "ずっと つづけられる", "usual": "いつもの", "fossil fuel": "せきゆや せきたんの ねんりょう", "barber": "かみのけを きる おみせ", "just in case": "もしもの ときの ため", "from the experience": "やってみて わかったことから", "lip": "くちびる", "farewell party": "おわかれの パーティー", "relatively": "くらべると わりと", "not always": "いつも 〜とは かぎらない", "be excited": "わくわく すること", "on your right": "みぎがわに", "have a headache": "あたまが いたいこと", "agree to": "〜を いいよと みとめること", "definitely": "まちがいなく", "strict": "きびしい", "artistic": "げいじゅつ てきな", "in conclusion": "まとめると", "ecosystem": "いきものたちの つながり", "be in trouble": "こまっていること", "prefer A to B": "Bより Aの ほうが すきなこと", "with a smile": "にこにこ わらって", "functional": "じっさいに やくに たつ", "keep in touch": "れんらくを とりあうこと", "believe it or not": "しんじられないかも しれないけど", "endangered": "ぜつめつ しそうな", "breed": "どうぶつを そだてて ふやすこと", "wrap": "つつむこと", "lead": "せんとうで みちびくこと", "do a favor": "たのみごとを きいてあげること", "arrive at": "〜に つくこと", "jewel": "キラキラの ほうせき", "fall in love with": "〜を すきに なること", "be in danger of": "〜の きけんが あること", "government": "くにを うごかす せいふ", "countryside": "いなか", "amount": "りょう・かず", "limited": "かぎられた すくない", "climate": "その ちいきの てんきの ようす", "out of order": "こしょうして つかえない", "human rights": "ひとが もつ たいせつな けんり", "surround": "まわりを かこむこと", "holy": "かみさまの ような とうとい", "instruction": "やりかたの せつめい", "waste": "むだに つかうこと", "weekly": "しゅうに いっかいの", "on the wall": "かべに", "magazine": "ざっし", "store": "ためて おくこと", "lazy": "なまけものの", "discrimination": "ふこうへいな さべつ", "fold": "おりたたむこと", "afraid": "こわがって", "all over": "〜じゅう ぜんぶに", "steam": "ゆげ", "pain": "いたみ", "chemical": "かがくの ぶっしつ", "check out": "しらべること", "capture": "つかまえること", "paper crane": "おりがみの つる", "be concerned with": "〜に かんけいしていること", "wet": "ぬれている", "arrest": "けいさつが つかまえること", "curious": "しりたがりの", "encourage to ～": "〜するように おうえんすること", "unfair": "ずるくて こうへいでない", "strange": "へんな・ふしぎな", "tired": "つかれている", "take a rest": "やすむこと", "statue": "どうや いしの ぞう", "law": "まもるべき ほうりつ", "check ～ out": "〜を かくにんすること", "stationery shop": "ぶんぼうぐの おみせ", "search for": "さがすこと", "in detail": "こまかく くわしく", "growth": "ふえて おおきく なること", "stationery": "えんぴつや ノートの ぶんぼうぐ", "carbon dioxide": "はくいきに ある きたい(にさんかたんそ)", "hear from": "〜から れんらくが くること", "wake": "めが さめること", "depend on": "〜に たよること", "bomb": "ばくはつする ばくだん", "resident": "そこに すんでいる ひと", "audience": "みている おきゃくさん", "brave": "ゆうきが ある", "extinguisher": "ひを けす しょうかき", "be likely to": "〜しそうなこと", "trade": "くにと くにの ぼうえき", "hall": "ろうか・ひろい へや", "be in need of": "〜が ひつようなこと", "fill in": "ひつようなことを かきこむこと", "run": "おみせなどを やっていくこと", "flight": "ひこうきの びん", "get lost": "みちに まようこと", "renewable": "なんども つかえる", "all the time": "いつも ずっと", "ask someone for": "だれかに 〜を おねがいすること", "donate": "ただで あげる・きふすること", "nest": "とりの す", "import": "がいこくから かいいれること", "secret": "ひみつ", "given": "あたえられた", "unused": "まだ つかっていない", "debate": "テーマを きめて する とうろん", "note": "おさつ（おかね）", "awake": "めが さめている", "fall": "おちること", "crazy": "むちゃくちゃな", "for instance": "たとえば", "discussion": "はなしあい", "drop by": "ちょっと よること", "metal": "きんぞく", "relation": "かんけい", "colony": "べつの くにに しはいされた とち", "past": "むかしの", "succeed": "うまく いくこと", "certain": "まちがいない", "be amazed at": "〜に びっくりすること", "modern": "いまふうの", "get rid of": "いらないものを なくすこと", "affect": "〜に えいきょうを あたえること", "match": "しあい", "be satisfied with": "〜に まんぞくしていること", "quietly": "しずかに", "for example": "たとえば", "fall asleep": "ねむりに つくこと", "signal": "しんごう", "protest": "はんたいだと こうぎすること", "extinction": "いきものが いなくなる ぜつめつ", "belong to": "〜の ものであること", "pleased": "よろこんで", "uniform": "せいふく", "neighbor": "となりの ひと", "leg": "あし", "army": "りくぐん（ぐんたい）", "universe": "うちゅう", "effective": "こうかが ある", "pursue": "おいかけて もとめること", "step": "いっぽ・かいだん", "an average of": "へいきんで 〜", "relate to ～": "〜に かんけいさせること", "condition": "ようす・じょうたい", "burden": "おもい ふたん", "wood": "もくざい・き", "shade": "ひかげ", "quiet": "しずかな", "billion": "10おく", "graduation": "がっこうの そつぎょう", "heat": "あつい ねつ", "get tired": "つかれること", "successful": "せいこうした", "weapon": "たたかいの ぶき", "necessary": "どうしても ひつような", "someone in need": "たすけが ひつような ひと", "be scared of": "〜が こわいこと", "consumer": "ものを かう ひと", "depend": "たよること", "trust": "しんようすること", "film": "えいが", "loss": "なくすこと", "honey": "ハチの あまい みつ", "suddenly": "きゅうに", "disaster": "じしんなどの さいがい", "pass by": "よこを とおりすぎること", "charge": "でんきを ためること", "resource": "やくに たつ しげん", "police officer": "けいさつかん", "ashamed": "はずかしくて", "image": "え・イメージ", "be familiar with": "〜を よく しっていること", "planet": "ちきゅうのような わくせい", "exception": "ほかと ちがう れいがい", "certainly": "たしかに", "surely": "たしかに", "device": "きかい・どうぐ", "arm": "うで", "be responsible for": "〜の せきにんが あること", "treasure": "たからもの", "call back": "おりかえし でんわすること", "die out": "いなくなる・ぜつめつすること", "sit down": "すわること", "look after": "せわを すること", "mind": "こころ", "take it back": "とりもどすこと", "fly": "そらを とぶこと", "tear": "なみだ", "employee": "やとわれて はたらく ひと", "survival": "いきのこること", "species": "いきものの しゅるい", "lawyer": "ほうりつの せんもんか べんごし", "parking lot": "くるまを とめる ところ", "success": "せいこう", "try hard": "いっしょうけんめい やること", "himself": "かれ じしんを", "sleepy": "ねむい", "away": "はなれて", "dislike": "きらうこと", "excuse": "ゆるすこと", "Long time no see.": "ひさしぶり", "That's all right.": "だいじょうぶだよ", "I appreciate it.": "ありがとう、たすかるよ", "I owe you one.": "こんど おかえし するね", "Can I ask a question?": "しつもん して いい？", "Can I try it on?": "きてみても いい？", "May I borrow this book?": "この ほん かりても いい？", "Shall I help you?": "てつだおうか？", "Let me help you.": "てつだわせてね", "I'll call you back.": "あとで でんわ かけなおすね", "Tell me if you need anything.": "なにか いるなら いってね", "I'll be right back.": "すぐ もどるね", "Why don't you ask her?": "かのじょに きいてみたら？", "Let's take a break.": "ちょっと やすもう", "Shall we watch a movie?": "えいが みようか？", "Are you busy now?": "いま いそがしい？", "I'm ready to go.": "でかける じゅんび できたよ", "I'm running late.": "ちょっと おくれそう", "I forgot my homework.": "しゅくだいを わすれちゃった", "I need my dictionary.": "じしょが いるんだ", "Please hand in your report.": "レポートを だしてね", "I left school early.": "はやびけ したよ", "I have to study for the exam.": "テストの べんきょうを しなきゃ", "The class is over.": "じゅぎょうが おわったよ", "Could you help me with math?": "さんすう てつだってくれる？", "Can I help you?": "なにか おさがしですか", "Can I try this on?": "これ きてみても いい？", "I'm looking for a gift.": "プレゼントを さがしてるんだ", "Can you wrap it, please?": "つつんで もらえますか", "I'd like a salad, please.": "サラダを ください", "I'm ready to order.": "ちゅうもん できます", "No tomatoes, please.": "トマトは ぬいてください", "The food is delicious.": "りょうりが おいしい", "It's too spicy for me.": "わたしには からすぎる", "Could we have the bill?": "おかいけい おねがいします", "I'll have the same.": "おなじものを ください", "Save some for me.": "ちょっと のこしておいてね", "We missed the train.": "でんしゃに のりおくれた", "This seat is taken.": "この せきは あいてないよ", "I got off at the wrong station.": "ちがう えきで おりちゃった", "Please tell me when to get off.": "おりる とき おしえてね", "Take an umbrella with you.": "かさを もっていってね", "Spring is my favorite season.": "はるが いちばん すきな きせつ", "I love autumn leaves.": "こうようが だいすき", "I have a fever.": "ねつが あるんだ", "I have a headache.": "あたまが いたい", "I caught a cold.": "かぜを ひいちゃった", "My stomach hurts.": "おなかが いたい", "I need to see a doctor.": "おいしゃさんに みてもらわなきゃ", "Don't stay up late.": "よふかし しないでね", "I'm a little tired.": "ちょっと つかれた", "I like this one.": "これが すき", "I don't like spicy food.": "からい たべものは すきじゃない", "I agree with you.": "きみに さんせい", "I prefer tea to coffee.": "コーヒーより おちゃが すき", "This is my favorite song.": "これが いちばん すきな うた", "I'm interested in art.": "びじゅつに きょうみが ある", "That's too difficult for me.": "わたしには むずかしすぎる", "The game starts soon.": "しあいが もうすぐ はじまる", "We won the match.": "しあいに かったよ", "We lost by one point.": "1てんさで まけた", "I'm a little worried.": "ちょっと しんぱい", "Let's cheer for them.": "みんなを おうえんしよう", "That was a great game.": "すごい しあいだった", "Please leave a message.": "でんごんを のこしてね", "Can I speak to Ken?": "ケンさん いますか", "My phone is out of battery.": "ケータイの でんちが きれた", "Check your email, please.": "メールを みてね", "Sorry, wrong number.": "ごめん、ばんごう まちがえた", "Please call me back.": "おりかえし でんわしてね", "I lost my wallet.": "さいふを なくした", "I forgot my ticket.": "きっぷを わすれた", "I left it at home.": "いえに おいてきちゃった", "My shoes are wet.": "くつが ぬれてる", "I'm proud of you.": "きみを ほこりに おもうよ", "Keep trying.": "あきらめずに つづけて", "That's too bad.": "それは ざんねんだね", "I'll be back.": "もどってくるね", "I have an appointment.": "やくそくが あるんだ", "I need to make a copy.": "コピーを とらなきゃ", "I was stuck in traffic.": "じゅうたいに はまってた", "I'm on my break.": "いま きゅうけいちゅう", "This is my first time.": "これが はじめてなんだ", "It's my piece of cake.": "それは わたしの ケーキだよ"});

Object.assign(EASY, {"rose": "のぼった（あがった）", "hold": "てに もつ・にぎること"});

Object.assign(EASY, {"as a result": "けっか として", "in the past": "むかしに", "nowadays": "いまどきは", "gain": "てに いれること", "extra": "よぶんの", "clothing": "きもの・ふくるい", "dress up": "おしゃれを すること", "details": "こまかい ところ", "melt": "とけること", "injury": "けが", "silence": "しずかで おとが ないこと", "tight": "きつい・せまい", "sharp": "するどい", "immediately": "すぐに", "experiment": "じっけん", "material": "ものを つくる ざいりょう", "traffic": "くるまの ながれ・こうつう", "distance": "はなれている きょり", "prefer": "そっちの ほうが すきなこと", "impression": "うけた かんじ", "item": "ひとつの しなもの", "profit": "もうけ", "sink": "しずむこと", "expert": "くわしい せんもんか", "silly": "おばかな", "wealthy": "おかねもちの", "divide": "わけること", "ignore": "しらんぷりすること", "overcome": "のりこえること", "narrow": "はばが せまい", "confuse": "ごちゃごちゃに なること", "asleep": "ねむっている", "in particular": "とくに", "take over": "ひきつぐこと", "in addition": "そのうえ・さらに", "be filled with": "〜で いっぱいなこと", "refrigerator": "たべものを ひやす れいぞうこ", "do me a favor": "おねがいを きいてもらうこと", "get back": "とりもどすこと", "keep in mind": "おぼえておくこと", "on the way to": "いく とちゅうで", "put down": "したに おくこと", "rely on": "〜に たよること", "appeal to": "〜に うったえること", "in case": "もしもの ときの ため", "on average": "へいきんすると", "on purpose": "わざと", "stay away from": "〜から はなれていること", "suffer from": "〜で くるしむこと", "succeed in": "〜に せいこうすること", "after all": "けっきょく", "differ from": "〜と ちがうこと", "participate in": "〜に さんかすること", "sooner or later": "いつかは", "similar to": "〜に にていること", "turn down": "ことわること", "fill out": "ひつようなことを かきこむこと", "dig": "あなを ほること", "muscle": "からだの きんにく", "bite": "かむこと", "treat": "あつかう・もてなすこと", "arrival": "つくこと", "degree": "ていど・どあい", "attitude": "たいどの ようす", "belief": "しんじていること", "demonstrate": "じっさいに みせて しめすこと", "formal": "きちんとした・せいしきの", "allow": "いいよと ゆるすこと", "argument": "いいあい・ぎろん", "ancestor": "むかしの せんぞ", "capital": "しゅと・もとで", "praise": "ほめること", "punish": "ばつを あたえること", "negative": "うちけす・マイナスの", "consist": "〜から できていること", "criticize": "わるい ところを いうこと", "promote": "もっと さかんに すること", "childhood": "こどもの ころ", "accomplish": "やりとげること", "combine": "ひとつに あわせること", "responsible": "せきにんが ある", "stomach": "おなか・い", "vision": "みらいの イメージ", "expansion": "ひろがること", "ease": "らくなこと", "elect": "えらんで きめること", "unit": "ひとまとまりの たんい", "manner": "やりかた", "govern": "くにを おさめること", "enforcement": "ルールを まもらせること", "talented": "さいのうが ある", "firm": "しっかりした", "community": "みんなの あつまり・ちいき", "force": "ちから", "impressive": "こころに のこる すごい", "salary": "もらう おきゅうりょう", "deal": "あつかうこと", "prompt": "すぐの", "vote": "せんきょで えらぶこと", "range": "はんい", "vital": "とても たいせつな", "estate": "ざいさん", "unknown": "まだ しられていない", "grant": "もらえる おかね", "perceive": "かんじとること", "especially": "とくに", "client": "おきゃくさん", "mysterious": "ふしぎな", "steel": "かたい てつ（はがね）", "concept": "かんがえかた", "nevertheless": "それでも", "manufacturer": "ものを つくる かいしゃ", "effect": "こうか・えいきょう", "encounter": "ばったり であうこと", "accuse": "わるいと せめること", "briefly": "みじかく", "lack": "たりないこと", "essay": "ぶんしょう", "approach": "ちかづくこと", "bear": "がまんすること", "natural": "しぜんの・あたりまえの", "administration": "うんえいする ところ", "production": "ものを つくること", "qualify": "しかくを とること", "previously": "まえに", "fee": "はらう りょうきん", "negotiation": "はなしあい", "extremely": "ものすごく", "detailed": "こまかい", "maximum": "いちばん おおきい", "improvement": "よくなること", "credit": "しんよう", "debt": "かりた おかね（しゃっきん）", "therapy": "ちりょう", "storage": "しまっておくこと", "academic": "べんきょう・がくもんの", "concern": "しんぱいすること", "strain": "ぴんと はること", "role": "やくわり", "recent": "さいきんの", "mate": "なかま・ともだち", "distinguish": "みわけること", "sophisticated": "せんれんされた おしゃれな", "upset": "こころが みだれること", "disturb": "じゃまを すること", "intense": "はげしい", "polite": "れいぎ ただしい", "competition": "きょうそう", "inquiry": "といあわせ", "bind": "しばること", "behavior": "ふるまい", "earn": "はたらいて かせぐこと", "structure": "つくり・こうぞう", "rapidly": "すばやく", "prior": "まえの", "assessment": "ひょうか", "engaged": "いそがしく とりくんでいること", "court": "さいばんしょ・なかにわ", "enable": "できるように すること", "unfortunately": "ざんねんなことに", "representation": "あらわすこと", "procedure": "てじゅん", "asset": "ざいさん", "dump": "なげすてること", "citizen": "まちの ひと・こくみん", "occupation": "しごと・しょくぎょう", "restore": "もとに もどすこと", "significance": "たいせつさ", "failure": "しっぱい", "earnings": "かせいだ おかね", "disease": "びょうき", "peer": "なかま", "isolate": "ひとつだけ はなすこと", "competitive": "きょうそうりょくが ある", "typical": "よく ある・だいひょうてきな", "compete": "きょうそうすること", "assault": "らんぼうな こうげき", "conviction": "つよい しんねん", "terrible": "とても ひどい", "bill": "しはらいの せいきゅうしょ", "emphasize": "とくに つよく いうこと", "weather": "てんき", "immigrant": "よそから きた いみん", "interpret": "いみを とらえること", "thick": "あつい", "status": "じょうたい・みぶん", "political": "せいじの", "partly": "いちぶは", "conscious": "きづいている", "operation": "そうさ・うごかすこと", "feature": "とくちょう", "consideration": "よく かんがえること", "diet": "しょくじ・しょくじせいげん", "necessarily": "かならずしも", "analysis": "こまかく しらべること", "conflict": "たいりつ・あらそい", "extreme": "きょくたんな", "source": "もとに なる もの", "objective": "めあて・もくひょう", "rural": "いなかの", "analyst": "ぶんせきする ひと", "controversial": "いけんが わかれる", "commission": "てすうりょう", "independent": "じぶんの ちからで やっていく", "proposed": "ていあんされた", "theory": "りろん・かんがえ", "fellow": "なかま", "extension": "のばすこと", "proper": "ちょうど よい・てきせつな", "beyond": "〜を こえた むこうに", "due": "きげんの", "existing": "いまある", "rebel": "はむかう ひと", "suffer": "くるしむこと", "democrat": "みんしゅしゅぎの ひと", "personally": "じぶん じしんで", "throughout": "ぜんたいに ずっと", "preserve": "そのまま とっておくこと", "slide": "すべること"});

Object.assign(EASY, {"murder": "ひとを ころす はんざい", "constantly": "いつも ずっと", "drift": "ながされて ただようこと", "result": "けっか", "priority": "さきに する じゅんばん", "joint": "ほねの つなぎめ", "viewer": "みる ひと", "satellite": "ちきゅうの まわりを まわる えいせい", "distant": "とおく はなれた", "delivery": "とどけること", "anxious": "しんぱいで ふあんな", "particular": "とくべつな ひとつの", "criticism": "わるい ところの してき", "appear": "あらわれること", "permission": "いいよと いう きょか", "deny": "ちがうと うちけすこと", "valuable": "とても ねうちが ある", "comprehensive": "ぜんぶを ふくむ", "properly": "ちゃんと", "vulnerable": "きずつきやすい", "directly": "まっすぐ・じかに", "occupy": "ばしょを とること", "vary": "いろいろ ちがうこと", "armed": "ぶきを もった", "convince": "なっとくさせること", "criminal": "はんざいの", "naked": "はだかの", "hide": "かくすこと", "recovery": "げんきに もどること", "bond": "つよい つながり", "portrait": "ひとの え（しょうぞうが）", "intervention": "あいだに はいって とめること", "consistent": "いつも おなじで ぶれない", "investigator": "しらべる ひと", "normally": "ふつうは", "conclude": "まとめて おわること", "development": "はってん・そだつこと", "desire": "つよく のぞむこと", "involvement": "かかわること", "minister": "だいじん", "patch": "あてぬの", "ethnic": "みんぞくの", "refer": "さんこうに すること", "current": "いまの", "ceiling": "へやの てんじょう", "philosopher": "てつがくしゃ", "potential": "ひめている ちから", "rough": "ごつごつした", "fundamental": "いちばん もとの きほんの", "association": "なかまの あつまり・きょうかい", "yield": "うみだすこと", "politician": "せいじか", "phenomenon": "おきる できごと（げんしょう）", "admit": "みとめること", "critical": "とても たいせつな・きびしい", "adapt": "あわせて かえること", "attempt": "やってみること", "impress": "こころに のこすこと", "submit": "だすこと・したがうこと", "bored": "たいくつしている", "civilized": "ぶんめいが すすんだ", "combat": "たたかい", "destruction": "こわすこと", "ally": "なかまに なること", "complete": "ぜんぶ そろった", "complicated": "ふくざつな", "mad": "おこった・くるった", "hate": "とても きらうこと", "reputation": "まわりの ひょうばん", "phase": "だんかい", "philosophy": "てつがく", "shooting": "さつえい・しゃげき", "contemporary": "いまの じだいの", "jury": "さいばんの ばいしんいん", "huge": "とても おおきい", "element": "もとに なる ようそ", "exist": "じっさいに あること", "occasion": "とくべつな とき", "accompany": "いっしょに ついていくこと", "virtually": "じっさい ほとんど", "withdraw": "ひっこめる・ひきだすこと", "leisure": "ひまな じかん", "mass": "おおきな かたまり", "mixture": "まざったもの", "overall": "ぜんたいの", "exposure": "そとに さらすこと", "term": "きかん・せんもんようご", "industry": "ものづくりの さんぎょう", "proud": "じまんに おもう", "concentration": "しゅうちゅう", "lawn": "しばふ", "compose": "くみたてる・さっきょくすること", "proportion": "わりあい", "confident": "じしんが ある", "manufacturing": "せいぞうしている", "multiple": "たくさんの・かけざん", "authority": "けんりょく・けんい", "swear": "ちかうこと", "attractive": "みりょくが ある", "union": "ひとつに まとまること", "prisoner": "つかまった ひと", "sight": "みること・しりょく", "prosecutor": "けんさつかん", "present": "いまの・しゅっせきして", "publication": "しゅっぱんぶつ", "dull": "つまらない・にぶい", "aspect": "ものごとの ひとつの めん", "via": "〜を とおって", "judgement": "はんだん", "observer": "かんさつする ひと", "tongue": "した・ことば", "defendant": "うったえられた ひと", "component": "ぶひん・せいぶん", "declare": "はっきり せんげんすること", "squeeze": "ぎゅっと しぼること", "passage": "ぶんしょうの ひとくぎり", "whom": "だれを", "split": "わける・さくこと", "capable": "できる ちからが ある", "concrete": "はっきりした・コンクリート", "remaining": "のこっている", "dependent": "たよっている", "argue": "じぶんの いけんを いいあうこと", "consequence": "そのあとの けっか", "outcome": "けっか", "heritage": "うけついだ いさん", "master": "しゅじん・たつじん", "voter": "とうひょうする ひと", "landscape": "けしき", "occasionally": "たまに", "practical": "じっさいに やくに たつ", "wipe": "ふくこと", "affair": "ものごと・できごと", "reward": "ごほうび", "advertise": "せんでんすること", "eventually": "けっきょく・やがて", "approval": "みとめること", "harmful": "からだに わるい", "suggestion": "ていあん", "contrast": "ちがいを くらべること", "absorb": "すいこむこと", "proposal": "ていあん", "historic": "れきしに のこる", "immediate": "すぐの", "knee": "ひざ", "apply": "あてはめる・もうしこむこと", "existence": "あること", "dismiss": "さがらせること", "factor": "げんいんの ひとつ", "constant": "ずっと かわらない", "prayer": "いのり", "supporter": "おうえんする ひと", "stimulate": "しげきを あたえること", "proof": "しょうこ", "appropriate": "ちょうど よい", "deserve": "それに ふさわしいこと", "establishment": "せつりつ", "definition": "ことばの いみの せつめい", "economic": "けいざいの", "convey": "つたえる・はこぶこと", "partnership": "きょうりょくの かんけい", "attorney": "べんごし", "index": "さくいん", "circumstance": "まわりの じょうきょう", "craft": "てづくりの わざ", "reject": "ことわること", "admission": "にゅうじょう・にゅうじょうりょう", "consumption": "つかって へらすこと", "bishop": "キリストきょうの しきょう", "fuel": "もやす ねんりょう", "economy": "けいざい・せつやく", "construct": "くみたてて つくること", "assistance": "てだすけ", "implement": "じっこうする・どうぐ", "peak": "やまの てっぺん", "sculpture": "ちょうこく", "symptom": "びょうきの しょうじょう", "dealer": "はんばいする ひと", "unlike": "〜と ちがって", "treaty": "くにどうしの やくそく", "comedy": "わらえる おはなし", "absolutely": "ぜったいに", "alliance": "どうめい", "evil": "わるい・じゃあくな", "suppose": "たぶん そうだと おもうこと", "entitle": "タイトルを つける・けんりを あたえる", "confidence": "じしん・しんらい", "rush": "いそいで すすむこと", "female": "めすの・じょせいの", "identity": "じぶんが じぶんである こと", "cooperation": "きょうりょく", "coalition": "いくつかが くむこと", "detect": "みつけだすこと", "alter": "かえること", "retirement": "しごとを やめること", "sensitive": "びんかんな", "export": "がいこくへ うること", "correspondent": "とくはいん", "duty": "やるべき つとめ・かんぜい", "attach": "はりつけること", "personality": "せいかく", "fully": "じゅうぶんに", "scheme": "けいかく", "install": "とりつけること", "ingredient": "りょうりの ざいりょう", "flood": "みずが あふれる こうずい", "election": "せんきょ", "despite": "〜なのに", "revolution": "せかいを かえる かくめい", "promotion": "しょうしん", "industrial": "さんぎょうの", "dramatic": "げきてきな", "lean": "かたむく・よりかかる", "exhibition": "てんじかい", "compromise": "おたがい ゆずって きめること", "anxiety": "しんぱい・ふあん", "relevant": "かんけいが ある", "observation": "かんさつ", "manager": "まとめる ひと（ぶちょう）", "defeat": "まかすこと", "surgery": "しゅじゅつ", "reaction": "はんのう", "abandon": "すてること", "crisis": "あぶない とき", "comfort": "らくにする・なぐさめること", "wise": "かしこい", "sustain": "ささえて つづけること", "hire": "やとうこと", "slip": "つるっと すべること"});

Object.assign(EASY, {"entirely": "ぜんぶ かんぜんに", "totally": "かんぜんに", "extensive": "ひろい はんいの", "employ": "やとうこと", "hang": "つるすこと", "context": "まえうしろの ながれ（ぶんみゃく）", "assumption": "たぶん こうだろうという かんがえ", "aid": "たすけ・えんじょ", "poll": "とうひょう・アンケート", "girlfriend": "おんなの ともだち", "coast": "うみべ・かいがん", "evolution": "だんだん かわる しんか", "recall": "おもいだすこと", "threat": "おどし・きょうい", "transform": "すがたを かえること", "method": "やりかた・ほうほう", "jail": "けいむしょ", "primitive": "むかしの・げんしてきな", "emerge": "あらわれること", "highlight": "いちばん めだつ ところ", "initiative": "じぶんから すすんで やること", "recommendation": "すいせん", "according": "〜に よると", "implication": "うらに ある いみ", "pregnant": "あかちゃんが おなかに いること", "breath": "いき", "employer": "やとう がわの ひと", "advertising": "こうこく", "equipment": "どうぐ・せつび", "addition": "つけたすこと", "decline": "ことわること", "male": "おとこ・おす", "suit": "ぴったり あうこと", "merely": "ただ 〜だけ", "appearance": "あらわれること・みため", "contribute": "やくに たつように おかねや ちからを だすこと", "extend": "のばすこと", "policy": "やりかたの ほうしん", "cope": "なんとか たいしょすること", "religion": "かみさまを しんじる しゅうきょう", "conclusion": "けつろん", "treatment": "あつかいかた・ちりょう", "alternative": "べつの えらびかた", "reverse": "はんたいの", "victim": "ひがいに あった ひと", "distinction": "はっきりした ちがい", "patient": "がまんづよい・かんじゃ", "state": "じょうたい", "forever": "いつまでも ずっと", "propose": "ていあんすること", "content": "なかみ", "superior": "もっと すぐれた", "preparation": "じゅんび", "congress": "アメリカの ぎかい", "regarding": "〜について", "party": "せいとう・パーティー", "finance": "おかねの やりくり", "financial": "おかねの", "embrace": "だきしめること", "resistance": "はむかう ていこう", "corridor": "ろうか", "background": "うしろの けしき・はいけい", "strike": "たたくこと", "educate": "きょういくすること", "fabric": "ぬの", "clerk": "じむの ひと・てんいん", "evidence": "しょうこ", "funding": "しきんを あつめること", "extraordinary": "ふつうでは ない すごい", "civilian": "ぐんじんでない ふつうの ひと", "maintenance": "いいじょうたいを たもつこと", "faith": "しんじる きもち", "alike": "よく にている", "grammar": "ことばの ぶんぽう", "remain": "のこる・そのままで いること", "carbon": "たんそ", "provision": "ひつようなものを あたえること", "region": "ちいき", "boundary": "さかいめ", "wisdom": "ちえ", "creation": "つくりだすこと", "greet": "あいさつすること", "block": "じゃまして とめること", "escape": "にげること", "innocent": "つみが ない", "distribution": "くばること・ひろがり", "exactly": "ちょうど・せいかくに", "continent": "ひろい たいりく", "arms": "ぶき", "public": "みんなの・こうきょうの", "council": "ぎかい・かいぎ", "suitable": "ぴったり あった", "secretary": "ひしょ", "politics": "せいじ", "accurate": "せいかくな", "conventional": "いままで どおりの", "organization": "だんたい・そしき", "moral": "どうとくの", "intellectual": "あたまを つかう・ちてきな", "particularly": "とくに", "founder": "はじめて つくった ひと", "emotional": "きもちの・かんじょうの", "infection": "びょうきが うつること", "transition": "うつりかわり", "author": "ほんを かいた ひと", "considerable": "かなり おおきい", "conduct": "おこない", "physician": "おいしゃさん", "achievement": "やりとげた こと", "witness": "もくげきした ひと", "focus": "ピントを あわせること", "federal": "れんぽうの", "associate": "むすびつけて かんがえること", "activist": "うんどうを する ひと", "primary": "いちばん さいしょの・おもな", "joy": "よろこび", "inspector": "けんさする ひと", "variation": "いろいろな かわりかた", "stupid": "おばかな", "appeal": "うったえること", "substance": "ぶっしつ", "regulation": "きまり・ルール", "bare": "はだかの・なにも ない", "suspect": "あやしいと うたがうこと", "income": "はいってくる おかね", "fault": "わるい ところ", "tissue": "からだの そしき・ティッシュ", "percentage": "わりあい（パーセント）", "personnel": "じんじ・しょくいん", "sudden": "きゅうな", "transfer": "べつの ところへ うつすこと", "solid": "かたい", "mess": "ぐちゃぐちゃ", "flee": "にげること", "drain": "みずを ぬくこと", "lecture": "こうぎ", "resolution": "かいけつ・かたい けつい", "advocate": "いいと すすめること", "bet": "かけを すること", "characteristic": "その ものらしい とくちょう", "cause": "げんいん", "commitment": "やくそく・せきにん", "involve": "ふくむ・まきこむこと", "expression": "あらわしかた", "investor": "おかねを だす とうしか", "humanity": "にんげん・にんげんらしさ", "contribution": "こうけん・きふ", "frequently": "なんども", "shrug": "かたを すくめること", "operator": "そうさする ひと", "interpretation": "いみの とらえかた", "rely": "たよること", "reduction": "へらすこと", "summit": "やまの ちょうじょう・しゅのうかいぎ", "hell": "じごく", "typically": "だいたい・たいてい", "issue": "もんだい・ごう", "rent": "やちん", "widely": "ひろく", "satisfaction": "まんぞく", "completely": "かんぜんに", "inflation": "ものの ねだんが あがること", "crop": "しゅうかくする さくもつ", "prosecution": "うったえて さばくこと", "imagination": "そうぞう", "curiosity": "しりたがる きもち", "tail": "しっぽ", "except": "〜を のぞいて", "string": "ひも・いと", "appoint": "にんめいすること", "military": "ぐんたいの", "conference": "かいぎ", "explanation": "せつめい", "atmosphere": "ふんいき・くうき", "examination": "しけん", "strongly": "つよく", "fear": "こわがること", "exclude": "のぞくこと", "discipline": "しつけ・きりつ", "potentially": "もしかすると", "extent": "ていど・おおきさ", "settlement": "うつりすむこと", "presence": "そこに いること", "basis": "もとに なる どだい", "commander": "しれいかん", "radical": "おおきく かえる・きゅうしんてきな", "individual": "ひとりひとりの", "journal": "にっき・ざっし", "entertainment": "たのしませる ごらく", "opposite": "はんたいの", "district": "ちいき", "historical": "れきしの", "bullet": "じゅうの たま", "revenue": "はいる おかね", "democracy": "みんなで きめる みんしゅしゅぎ", "legislation": "ほうりつを つくること", "breast": "むね", "actual": "ほんとうの", "eager": "とても したがっている", "psychological": "こころの", "refugee": "にげてきた なんみん", "origin": "はじまり", "initially": "さいしょは", "doubt": "ほんとうかなと うたがうこと", "laboratory": "じっけんしつ", "delight": "おおきな よろこび", "universal": "どこでも つうじる", "labor": "はたらくこと・ろうどう", "blood": "ち", "arise": "おきること", "mere": "ただの", "agenda": "はなしあう ぎだい", "terror": "きょうふ", "truly": "ほんとうに", "favor": "しんせつな こうい", "recession": "けいきが わるいこと", "aircraft": "ひこうき", "prison": "けいむしょ", "anniversary": "きねんび", "possibility": "できるかもしれない かのうせい", "sequence": "じゅんばんに つづくこと", "investigation": "しらべること", "depression": "おちこみ・ふけいき", "unless": "〜でない かぎり", "necessity": "ぜったい ひつようなこと", "supreme": "いちばん たかい・さいこうの", "severe": "とても きびしい", "apart": "はなれて", "crack": "ひび・われめ"});

Object.assign(EASY, {"depending": "〜しだいで", "household": "いえの かぞく", "laughter": "わらいごえ", "crime": "はんざい", "frighten": "こわがらせること", "mortgage": "いえを かう ための かりきん", "stroke": "いちげき・ひとふり", "shortage": "たりないこと", "property": "もちもの・ざいさん", "freeze": "こおること", "closely": "ぴったり・くわしく", "venture": "ぼうけんてきな しごと", "account": "ぎんこうこうざ", "edge": "はし・ふち", "environmental": "かんきょうの", "amendment": "なおして かえること", "fiber": "ほそい せんい", "restriction": "せいげん", "in order to": "〜する ために", "end up": "けっきょく 〜に なる", "expense": "かかる おかね", "similar": "にている", "pollution": "よごれ・おせん", "foundation": "どだい・せつりつ", "compare": "くらべること", "lead to": "〜に つながること", "more and more": "どんどん ふえること", "consume": "つかって へらすこと", "employment": "やとうこと", "by chance": "ぐうぜん", "betray": "うらぎること", "portable": "もちはこべる", "construction": "けんせつ", "convert": "べつのものに かえること", "currency": "おかね（つうか）", "in contrast": "それと くらべて", "additionally": "さらに", "in response to": "〜に こたえて", "at the same time": "どうじに", "preserved": "ほぞんされた", "be known as": "〜として しられている", "analyze": "こまかく しらべること", "sympathy": "おもいやり・どうじょう", "flexibility": "やわらかさ・じゆうさ", "reach out": "てを さしのべること", "for fear of": "〜を こわがって", "on account of": "〜の ため", "artificial": "にんげんが つくった", "prevent A from B": "AをBから ふせぐこと", "since then": "それ いらい", "turn A into B": "AをBに かえること", "fertilizer": "さくもつを そだてる ひりょう", "made of": "〜で できている", "make sure": "たしかめること", "tolerate": "がまんすること", "get along": "なかよく やること", "keep up with": "おくれずに ついていくこと", "cell": "からだの さいぼう", "invest in": "〜に おかねを だすこと", "embarrass": "はずかしがらせること", "enlarge": "おおきく すること", "brilliant": "とても すぐれた・かがやく", "vote for": "〜に とうひょうすること", "frequent": "なんども おきる", "rare": "めずらしい", "bank account": "ぎんこうこうざ", "locate": "ばしょを みつけること", "apply to": "〜に あてはめること", "politely": "ていねいに", "accidentally": "うっかり", "appointment": "やくそく・よやく", "luxury": "ぜいたく", "replacement": "いれかえ・かわりのもの", "in touch": "れんらくが とれて", "imitate": "まねること", "assignment": "わりあてられた しごと", "instrument": "がっき", "capable of": "〜が できる", "arrange": "ととのえる・ならべること", "take after": "〜に にていること", "guilty of": "〜の つみを おかして", "composer": "さっきょくか", "delete": "けすこと", "urgent": "いそぎの", "cruel": "ざんこくな", "celebration": "おいわい", "reflection": "はねかえり・うつること", "deposit": "おかねを あずけること", "apology": "あやまること", "deceive": "だますこと", "endure": "がまんすること", "disposal": "しょぶん・しまつ", "statistics": "かずの データ（とうけい）", "terminal": "いちばん おわりの", "formation": "かたちづくること", "envelope": "てがみの ふうとう", "quarrel": "けんか・いいあい", "from time to time": "ときどき", "in demand": "もとめられている", "to some extent": "ある ていど", "at any cost": "どんなことを しても", "lose face": "はじを かくこと", "answer for": "せきにんを とること", "insist on": "つよく いいはること", "in common": "きょうつうして", "be affected by": "〜の えいきょうを うけること", "in response": "〜に こたえて", "have effects on": "〜に えいきょうを あたえること", "five senses": "ごかん", "related to": "〜に かんけいする", "active": "かっぱつな", "immune": "めんえきが ある", "disorder": "ぐちゃぐちゃ・みだれ", "mental": "こころの", "at present": "いまは", "make a difference": "ちがいを うむこと", "exceptionally": "とくべつに", "as to": "〜について", "collapse": "くずれること", "insult": "ばかにすること", "isolated": "ひとつだけ はなれた", "punctual": "じかんを きちんと まもる", "frightened": "こわがった", "guarantee": "だいじょうぶと ほしょうすること", "blame": "わるいと せめること", "violate": "ルールを やぶること", "delay": "おくらせること", "immigrate": "べつの くにへ うつりすむこと", "instinct": "うまれつきの ほんのう", "strangely": "ふしぎなことに", "chase": "おいかけること", "pour": "どんどん そそぐこと", "pull away": "ひきはなすこと", "try out": "ためしてみること", "break into": "むりやり はいりこむこと", "call it a day": "きょうは おしまいに すること", "be awake": "めが さめていること", "brightness": "あかるさ", "have an effect on": "〜に えいきょうを あたえること", "be adjusted to": "〜に あわせて ちょうせいすること", "heart rate": "しんぱくすう", "be beneficial to": "〜に やくに たつこと", "what is called": "いわゆる", "check for": "しらべて かくにんすること", "over time": "じかんを かけて だんだん", "for some time": "しばらくの あいだ", "copyright": "つくった ひとの けんり（ちょさくけん）", "director": "かんとく", "in reality": "じっさいは", "claim to do": "〜すると いいはること", "it is common to hear": "よく きく ことだ", "bring": "もってくる・つれてくること", "throw away": "すてること", "environmentally": "かんきょうの めんで", "process": "てじゅん・かこうすること", "up to": "〜まで", "turn into": "〜に かわること", "cut down on": "へらすこと", "plastic bag": "ビニールぶくろ", "harm": "がい・きずつけること", "unbelievable": "しんじられない", "arrogant": "いばっている", "harbor": "ふねの みなと", "temper": "きしょう・かんしゃく", "legend": "いいつたえ（でんせつ）", "vague": "ぼんやりした", "harvest": "しゅうかく", "ruin": "だいなしに すること", "overtake": "おいこすこと", "restrict": "せいげんすること", "stock": "かぶ・ざいこ", "competitor": "きょうそう あいて", "spectator": "みている おきゃく", "explorer": "たんけんか", "concentrate on": "〜に しゅうちゅうすること", "laugh at": "〜を わらうこと", "well off": "おかねもちの", "straight on": "まっすぐ", "leave out": "のぞくこと", "the other": "もう いっぽうの", "leftover": "のこりもの", "because of": "〜の せいで", "efficiency": "むだのない こうりつ", "arrangement": "ならべかた・はいち", "prescription": "くすりの しょほうせん", "generously": "けちけちせず たっぷり", "do well": "うまく やること", "deadline": "しめきり", "temporarily": "いっときだけ", "provide A with B": "Aに Bを あげること", "fund": "しきん", "overlap": "かさなること", "collaboration": "いっしょに つくること", "detective": "たんてい・けいじ", "modify": "なおして かえること", "stir": "かきまぜること", "orbit": "ほしが まわる みち（きどう）", "emotionally": "かんじょうてきに", "evaluate": "ひょうかすること", "prospect": "これからの みこみ"});

Object.assign(EASY, {"detail": "こまかい ところ", "deal with": "たいしょすること", "result in": "けっか 〜に なること", "in charge of": "〜の たんとうで", "cope with": "なんとか たいしょすること", "dispose": "しまつ・はいき", "show up": "あらわれること", "carry out": "やりとげること", "due to": "〜が げんいんで", "defend": "まもること", "payment": "しはらい", "in practice": "じっさいには", "publisher": "ほんを だす かいしゃ", "be pleased with": "〜を よろこぶこと", "postpone": "あとに のばすこと", "fulfill": "みたすこと", "capacity": "はいる りょう", "doubtfully": "うたがって", "permanently": "ずっと", "critics": "ひょうろんか", "explorers": "たんけんか", "obstacle": "じゃまな しょうがいぶつ", "take A for granted": "Aを あたりまえと おもうこと", "pass out": "きを うしなうこと", "think over": "よく かんがえること", "put away": "かたづけること", "participant": "さんかする ひと", "react to": "〜に はんのうすること", "jealously": "やきもちを やいて", "in other words": "いいかえると", "associated with": "〜と かんけいした", "to start with": "まず さいしょに", "congratulations on": "〜の おいわい", "precious": "とても たいせつな", "specialize in": "〜を せんもんに すること", "neverthless": "それでも", "checkup": "けんこうしんだん", "health insurance": "けんこうほけん", "memory loss": "きおくを なくすこと", "inconvenience": "ふべん", "unusually": "いつもと ちがって", "amount to": "ぜんぶで 〜に なること", "in some way": "なんらかの ほうほうで", "be connected to": "〜に つながっていること", "be involved in": "〜に かかわっていること", "genetically": "いでんてきに", "be made from": "〜から つくられる", "major": "せんこうの かもく", "be threatened to": "〜に おびやかされること", "with luck": "うんが よければ", "offensive": "こうげきてきな・しつれいな", "abrupt": "きゅうな", "familiar": "よく しっている", "distributor": "おろしうりの ぎょうしゃ", "publicity": "せけんに しらせること", "separation": "わけて はなすこと", "reuse": "また つかうこと", "illustrate": "れいを あげて せつめいすること", "voluntarily": "じぶんから すすんで", "consciously": "わざと・きを つけて", "approximately": "だいたい", "peacefully": "おだやかに", "whistle": "くちぶえを ふくこと", "voyage": "ふねの こうかい", "envy": "うらやましがること", "exaggerate": "おおげさに いうこと", "refer to": "〜を さんこうに すること", "in trouble": "こまっている", "at best": "せいぜい", "except for": "〜を のぞいて", "in effect": "こうかが あって", "on demand": "もとめられたら すぐ", "transportation": "こうつう・ゆそう", "in general": "ふつうは", "expired": "きげんが きれた", "renew": "あたらしく しなおすこと", "attach to": "〜に とりつけること", "unexpected": "おもいがけない", "humidity": "しめりけ", "on duty": "とうばんで", "exact": "ちょうど・せいかくな", "warm": "あたたかい", "out of place": "ばちがいで", "relative": "くらべての・しんせき", "poison": "どく", "be effective at": "〜で こうかが ある", "feed": "えさを あげること", "container": "いれもの", "on the run": "にげて", "dedicate": "〜に うちこむこと", "revenge": "しかえし", "suspicious": "あやしい", "welfare": "しあわせ・ふくし", "interrupt": "じゃまして とめること", "bravely": "ゆうかんに", "tragedy": "かなしい できごと（ひげき）", "struggle with": "〜と たたかうこと", "instruct": "やりかたを おしえること", "get used to": "なれること", "out of date": "じだいおくれの", "in need of": "〜が ひつようで", "at a loss": "どうしていいか わからず", "within reach": "てが とどく ところに", "in a row": "いちれつに・れんぞくで", "be short of": "〜が たりないこと", "play a role in": "〜で やくわりを はたすこと", "large amount of": "たくさんの", "rug": "ゆかに しく しきもの", "digest": "ようやく・しょうかすること", "focus on": "〜に しゅうちゅうすること", "vocabulary": "しっている ことばの かず", "ignorance": "しらないこと", "commute": "つうきんすること", "incident": "できごと・じけん", "yell": "おおごえで さけぶこと", "impose": "むりに おしつけること", "parliament": "ぎかい・こっかい", "nursery school": "ほいくえん", "stand still": "じっと とまっていること", "incredible": "しんじられない", "in terms of": "〜の てんで", "for sure": "まちがいなく", "objection": "はんたい・いぎ", "outstanding": "とびぬけて すごい", "adequate": "じゅうぶんな", "mildly": "おだやかに", "scar": "きずあと", "hesitantly": "ためらって", "give out": "くばること", "insurance": "ほけん", "take down": "おろす・かきとめること", "put together": "まとめること", "account for": "〜を せつめいすること", "tourism": "かんこう", "commit": "うちこむ・まかせること", "put off": "あとに のばすこと", "relevant to": "〜に かんけいして", "differ": "ちがうこと", "keep up": "いじすること", "look over": "ざっと みること", "entitle to": "〜の しかくを あたえること", "cough": "せきを すること", "absorb in": "〜に むちゅうに なること", "spiritually": "せいしんてきに", "confess": "うちあけること", "reservation": "よやく", "translation": "ほんやく", "disadvantage": "ふりな ところ", "objectively": "きゃっかんてきに", "innocently": "むじゃきに", "location": "ばしょ", "oxygen": "さんそ", "do away with": "なくすこと", "neglect": "ほうっておくこと", "be obliged to": "〜しなければ ならないこと", "donation": "きふ", "exhibit": "しめすこと", "principal": "いちばん おもな・こうちょう", "product": "せいひん", "in short": "ようするに", "persuasion": "せっとく", "migrate": "うつりすむこと", "logical": "すじみちが とおっている", "get away with": "もって にげること", "accuracy": "せいかくさ", "laundry": "せんたくもの", "complain of": "〜の ふまんを いうこと", "intensive": "しゅうちゅうてきな", "look through": "ひととおり しらべること", "budget": "よさん", "liquid": "えきたい", "applause": "はくしゅ", "mammal": "ほにゅうるい", "blame for": "〜の せきにんを せめること", "precise": "せいかくな", "see in": "なかへ あんないすること", "visually": "めで みて", "astonish": "とても びっくりさせること", "distract": "きを そらすこと", "in place": "きまった ところに", "figure": "かたち・すがた", "accomplishment": "やりとげた せいか", "suburb": "まちの こうがい", "drag": "ひきずること", "mineral": "いわや どじょうの せいぶん（ミネラル）", "tremble": "ぶるぶる ふるえること", "stay up": "よふかしすること", "genuine": "ほんものの", "needlessly": "むだに", "in exchange": "ひきかえに", "deaf": "みみが きこえない", "masterpiece": "すばらしい さくひん", "in stock": "ざいこが あって", "deliver": "とどけること", "create": "つくりだすこと", "tropical": "ねったいの", "act on": "〜に もとづいて うごくこと", "altogether": "ぜんぶで・まったく", "insist": "つよく いいはること", "hesitation": "ためらい", "persist in": "あきらめずに やりとおすこと", "in vain": "むだに", "off duty": "しごとが やすみで", "live on": "いきつづけること", "illustration": "ずや え・じつれい", "advertisement": "こうこく", "pull down": "ひきおろす・とりこわすこと", "investigate": "しらべること", "description": "せつめい", "punishment": "ばつ", "flame": "ほのお"});

Object.assign(EASY, {"ambulance": "きゅうきゅうしゃ", "impossible": "ぜったい できない", "be accustomed to": "〜に なれている", "in danger of": "〜の きけんが あって", "in turn": "じゅんばんに", "worthy of": "〜に ふさわしい", "look up to": "そんけいすること", "add to": "つけたす・ふやすこと", "immigration": "べつの くにへ うつりすむこと", "make up": "ようい・かたづけ・なかなおり", "affection": "やさしい あいじょう", "by heart": "まる おぼえして", "academically": "べんきょうの めんで", "relieve": "らくに してあげること", "historian": "れきしの せんもんか", "democratic": "みんなで きめる", "abstract": "かたちの ない・ちゅうしょうてきな", "excess": "おおすぎること", "trait": "その ひとらしい とくちょう", "assess": "ひょうかすること", "troop": "ぐんぜい・むれ", "output": "つくりだす りょう", "assist": "てつだうこと", "welcome": "かんげいされる", "ensure": "かならず そうなるように すること", "classical": "むかしからの こてんの", "anger": "いかり", "virtue": "よい こころ・とく", "seat": "せき・すわらせること", "tremendous": "とても おおきい", "grand": "ごうかで おおきい", "guide": "あんないする ひと", "vessel": "いれもの・ふね", "interfere": "よけいな くちだし・じゃまをすること", "patience": "がまんづよさ", "practically": "じっさいに・ほとんど", "elaborate": "てが こんだ", "motive": "やる きっかけ（どうき）", "minimum": "いちばん ちいさい", "technical": "ぎじゅつの・せんもんてきな", "similarity": "にている ところ", "hunger": "おなかが すくこと・うえ", "perception": "かんじとること", "candidate": "せんきょなどの こうほ", "mystery": "なぞ・ふしぎ", "dignity": "けだかさ（いげん）", "rude": "しつれいな", "ritual": "ぎしき", "adjust": "ちょうどよく ちょうせいすること", "spoil": "だいなしに する・あまやかすこと", "composition": "くみたて・さくひん", "talent": "さいのう", "ultimate": "いちばん さいごの・きゅうきょくの", "telescope": "とおくを みる ぼうえんきょう", "exhaust": "つかれはてさせること", "instant": "ほんの いっしゅん", "gear": "はぐるま・ギア", "willing": "すすんで やる きが ある", "wage": "はたらいて もらう おかね", "smart": "あたまが いい", "complexity": "ふくざつさ", "critic": "ひひょうする ひと", "friendly": "ともだちみたいに やさしい", "consequently": "そのけっか", "colleague": "しごとの なかま", "servant": "つかえる ひと（めしつかい）", "Muslim": "イスラムきょうの ひと", "seed": "しょくぶつの たね", "cultivate": "はたけを たがやすこと", "awful": "とても ひどい", "lung": "いきを する はい", "refrain from": "〜を がまんして やめること", "lord": "りょうしゅ・しはいしゃ", "beg": "おねがいと たのみこむこと", "recognition": "みとめること", "legal": "ほうりつの・ごうほうの", "liberty": "じゆう", "confine": "せまく とじこめること", "charm": "みりょく", "excessive": "やりすぎの", "satisfactory": "まんぞくできる", "scatter": "まきちらすこと", "resist": "はむかうこと", "resolve": "かいけつする・けっしんすること", "false": "まちがった", "eliminate": "とりのぞくこと", "socially": "しゃかいてきに", "pray": "いのること", "ray": "ひかりの すじ", "maker": "つくる かいしゃ", "ministry": "くにの しょうちょう", "explosion": "ばくはつ", "cure": "びょうきを なおすこと", "impact": "つよい えいきょう・しょうげき", "economics": "けいざいの がくもん", "pupil": "せいと", "unusual": "めずらしい", "civil": "しみんの", "counter": "はむかうこと", "protein": "からだを つくる タンパクしつ", "mutual": "おたがいの", "guilty": "つみが ある", "fascinate": "むちゅうに させること", "plain": "かざりのない・わかりやすい", "pioneer": "はじめて きりひらく ひと", "sweep": "ほうきで はくこと", "display": "ならべて みせること", "aggressive": "こうげきてきな", "infant": "あかちゃん", "means": "ほうほう・てだて", "insect": "むし", "painful": "いたい", "circuit": "でんきの かいろ・じゅんかい", "regime": "せいけん", "sacrifice": "ぎせい", "devise": "くふうして かんがえだすこと", "intimate": "とても したしい", "relief": "ほっと すること", "vice": "だいりの・ふくの", "constitution": "けんぽう・なりたち", "essentially": "ほんしつてきに", "deliberately": "わざと・しんちょうに", "tide": "うみの しお", "plot": "はなしの すじ・たくらみ", "industrialize": "さんぎょうを さかんに すること", "aggression": "こうげき・しんりゃく", "confirm": "たしかめること", "cruise": "ふねで たびすること", "minority": "すくないほうの グループ", "odd": "へんな・きすう", "dominate": "しはいすること", "obligation": "やらなければ ならない つとめ", "blast": "ばくはつの かぜ", "nerve": "からだの しんけい", "logic": "すじみち（ろんり）", "depress": "がっかりさせること", "peculiar": "へんで かわった", "urge": "つよく すすめること", "institution": "せいど・しせつ", "facility": "しせつ", "unpleasant": "いやな きもちの", "elementary": "はじめの・しょきゅうの", "spiritual": "こころの", "swallow": "のみこむこと", "honor": "めいよ", "traffic jam": "こうつうじゅうたい", "inclined": "かたむいた・〜しがち", "owe": "かりが あること", "accustomed": "なれている", "confusion": "こんらん", "companion": "いっしょに いる なかま", "suppress": "おさえつけること", "pile": "つみかさね", "cover": "おおうこと", "distinct": "はっきり ちがう", "conservation": "まもって のこすこと", "behalf": "〜の かわりに", "perspective": "ものの みかた", "goal": "もくひょう・ゴール", "divorce": "りこん", "inhabitant": "そこに すむ ひと", "passive": "うけみの", "subtle": "びみょうな", "pursuit": "おいかけること", "dispute": "いいあい・ろんそう", "intelligence": "ちのう", "bow": "おじぎ", "firmly": "しっかりと", "impulse": "とっさの きもち（しょうどう）", "comparison": "くらべること", "communist": "きょうさんしゅぎの ひと", "republic": "だいとうりょうの いる くに", "effectively": "こうかてきに", "shame": "はじ", "cash": "げんきん", "diminish": "だんだん へること", "positive": "まえむきな・じしんが ある", "empire": "おうの おさめる ていこく", "navy": "かいぐん", "leap": "ぴょんと とぶこと", "insight": "ふかい みとおし", "newly": "あたらしく", "cop": "けいかん", "crown": "おうかんむり", "nod": "うなずくこと", "investment": "おかねを だす とうし", "constitute": "〜を かたちづくること", "initial": "さいしょの", "division": "わけること・ぶしょ", "preference": "すきな ほう", "grave": "おはか", "found": "あたらしく つくること", "reference": "さんこう", "profession": "せんもんの しごと", "undergo": "けいけんすること", "cave": "ほらあな", "fancy": "くうそう", "blink": "まばたき", "rid": "とりのぞくこと", "privilege": "とくべつな けんり", "rating": "ひょうか", "weigh": "おもさを はかること", "retain": "もちつづけること", "overwhelming": "あっとうてきな", "massive": "とても おおきい", "desirable": "のぞましい"});

Object.assign(EASY, {"application": "あてはめること・もうしこみ", "gene": "いでんしの じょうほう", "contract": "けいやく・やくそく", "regardless": "〜に かまわず", "bury": "つちに うめること", "absolute": "かんぜんな", "precisely": "せいかくに", "parking": "ちゅうしゃじょう", "ad": "こうこく", "editor": "ほんを へんしゅうする ひと", "killer": "ひとを ころす ひと", "appetite": "たべたい きもち（しょくよく）", "racial": "じんしゅの", "gay": "どうせいを すきな", "definite": "はっきりした", "pose": "ポーズ・しせい", "bang": "ドンと たたく・おおきな おと", "burst": "はじけること", "absence": "いないこと・けっせき", "inferior": "おとっている", "assure": "だいじょうぶと いうこと", "acknowledge": "みとめること", "gaze": "じっと みつめること", "load": "にもつを つむこと", "inevitable": "さけられない", "enthusiasm": "もえる じょうねつ", "as a matter of fact": "じつは", "grace": "めぐみ・ゆうが", "distort": "ねじ まげること", "arctic": "ほっきょくの", "obsession": "あたまから はなれない おもい", "obey": "いうことを きくこと", "rule out": "のぞくこと", "manipulate": "うまく あやつること", "sue": "うったえること", "get rif of": "とりのぞくこと", "Buddhist": "ぶっきょうの ひと", "as far as I know": "しっている かぎりでは", "extract": "ぬきとること", "indigenous": "もともと そこに いる", "slavery": "どれいの せいど", "destination": "いきさき", "designate": "えらんで さしてきめること", "domain": "しはいする ちいき", "infrastructure": "せいかつの きばん", "provoke": "おこらせる・しげきすること", "sole": "ただ ひとつの", "convict": "ゆうざいに すること", "apply for": "もうしこむこと", "fatigue": "つかれ", "utter": "まったくの", "stern": "きびしい", "forecast": "よそうすること", "architect": "けんちくか", "lessen": "へらすこと", "tumor": "からだの できもの（しゅよう）", "dormitory": "がくせいの りょう", "thrust": "ぐいと つきあげること", "handout": "くばる プリント", "addicted": "やめられなく なった", "kindergarten": "ようちえん", "accommodate": "とめてあげる・いれること", "obscure": "はっきり しない", "resign": "やくを やめること", "grocery": "しょくりょうひん", "toll": "とおる ための りょうきん", "stiff": "かたい", "put up with": "がまんすること", "induce": "ひきおこすこと", "withstand": "たえること", "sanitation": "せいけつな かんきょう", "conceal": "かくすこと", "isolation": "ひとつだけ はなすこと", "prejudice": "かたよった おもいこみ", "souvenir": "おみやげ", "supervisor": "じょうし", "soak": "みずに ひたすこと", "supplement": "おぎなうもの", "drought": "あめが ふらない ひでり", "penetrate": "つきぬけること", "conform": "ルールに したがうこと", "scarce": "すくなくて たりない", "thorough": "てっていした", "predator": "ほかの いきものを たべる どうぶつ", "beverage": "のみもの", "emperor": "こうてい・てんのう", "soar": "たかく まいあがること", "embarrassed": "はずかしい", "famine": "たべものが たりないこと", "bureau": "じむきょく", "extinct": "ぜつめつした", "roast": "あぶって やくこと", "along with": "〜と いっしょに", "make fun of": "〜を ばかにして わらうこと", "conquer": "せいふくすること", "converse": "はんたいの", "revise": "なおして あたらしくすること", "dip": "ちょっと ひたすこと", "optimistic": "まえむきで らくてんてきな", "expire": "きげんが きれること", "imperial": "ていこくの", "hierarchy": "うえした の じゅんばん", "erosion": "けずられること", "evoke": "よびおこすこと", "earnest": "まじめな", "get by": "なんとか やっていくこと", "savage": "あらあらしい・どうもうな", "spur": "しげき", "eyesight": "めの みえかた", "utilize": "うまく つかうこと", "accommodation": "とまる ところ", "starve": "うえて おなかが すくこと", "in spite of": "〜なのに", "organ": "からだの ぞうき", "integrate": "ひとつに まとめること", "magnificent": "とても りっぱな", "pastime": "ひまつぶしの たのしみ", "enrich": "ゆたかに すること", "refund": "おかねを はらいもどすこと", "germ": "びょうきの ばいきん", "descend": "おりること", "irrelevent": "かんけいない", "endow": "きふすること", "fingerprint": "ゆびの もんよう（しもん）", "vending machine": "じどうはんばいき", "compile": "あつめて まとめること", "by degrees": "だんだん", "approve": "みとめること", "compliment": "ほめことば", "hang up": "でんわを きること", "overwhelm": "あっとうすること", "break out": "きゅうに おこること", "watch out": "きを つけること", "pull off": "もぎとる・うまく やりとげること", "tame": "どうぶつを ならすこと", "ambition": "おおきな のぞみ（やぼう）", "scholarship": "がくひの えんじょ（しょうがくきん）", "spouse": "けっこん あいて", "shrink": "ちぢむこと", "document": "しょるい", "nap": "ひるね", "injection": "ちゅうしゃ", "endanger": "あぶなく すること", "basin": "まわりが やまの ぼんち", "stem": "しょくぶつの くき", "hand in": "ていしゅつすること", "be engaged in": "〜に たずさわっていること", "retrieve": "とりもどすこと", "in shape": "けんこうな", "consist of": "〜から できている", "even if": "たとえ 〜でも", "abolish": "なくすこと", "ugly": "みにくい", "get over": "のりこえること", "modest": "ひかえめな", "bloom": "はなが さくこと", "assign": "わりあてること", "architecture": "けんちく", "sparkle": "きらきら ひかること", "fragment": "こわれた かけら", "fare": "のりものの りょうきん", "prey": "えじき", "devastate": "めちゃくちゃに すること", "in contrast to": "〜と くらべて", "nutrition": "えいよう", "low-income": "しゅうにゅうが すくない", "leak": "もれること", "protocol": "れいぎ・てじゅん", "toxic": "どくの ある", "documentary": "じじつを きろくした", "acute": "するどい・きゅうせいの", "prohibit": "きんしすること", "organic": "むのうやくの", "exclusive": "ほかを いれない", "sincere": "まじめで しょうじきな", "vow": "ちかい", "layer": "かさなった そう", "sit up": "せすじを のばして すわること", "explode": "ばくはつすること", "irrigation": "はたけに みずを ひくこと", "a bunch of": "たくさんの", "humid": "しめっぽい", "salty": "しおからい", "invade": "せめこむこと", "stubborn": "がんこな", "harsh": "とても きびしい", "prolong": "ながく のばすこと", "humble": "けんきょな", "refuge": "ひなん", "cut down": "へらすこと", "bold": "ゆうかんな", "lately": "さいきん", "tuition": "じゅぎょうりょう", "vivid": "あざやかな", "out of stock": "ざいこ ぎれ", "comprehend": "よく りかいすること", "accumulate": "どんどん たまること", "summon": "よびだすこと", "restrain": "おさえること"});
